"use client";

import { useMemo, useState } from "react";
import { AppShell } from "@/components/layout/app-shell";
import { Modal } from "@/components/ui/modal";
import { Badge } from "@/components/ui/badge";
import { useAppStore } from "@/store/app-store";
import { formatCurrency } from "@/lib/utils";
import { BookOpen, Check, Copy, CreditCard, Eye, Plus, Search, ShoppingBag, Sparkles, Store, Users } from "lucide-react";

export default function StorePage() {
  const store = useAppStore();
  const [query, setQuery] = useState("");
  const [type, setType] = useState("all");
  const [checkoutId, setCheckoutId] = useState<string | null>(null);
  const [customerName, setCustomerName] = useState("");
  const [customerEmail, setCustomerEmail] = useState("");
  const [successCode, setSuccessCode] = useState("");
  const [checkoutBusy, setCheckoutBusy] = useState(false);
  const [paymentMessage, setPaymentMessage] = useState("");
  const [createOpen, setCreateOpen] = useState(false);
  const [productName, setProductName] = useState("");
  const [productType, setProductType] = useState<"book" | "template" | "membership" | "bundle">("book");
  const [productPrice, setProductPrice] = useState(390000);
  const products = useMemo(() => store.products.filter((item) => item.status === "active" && (type === "all" || item.type === type) && `${item.name} ${item.description}`.toLowerCase().includes(query.toLowerCase())), [store.products, type, query]);
  const active = store.products.find((item) => item.id === checkoutId);
  const checkout = async () => { if (!active) return; setCheckoutBusy(true); setPaymentMessage(""); const email = customerEmail.trim() || "demo@example.com"; const order = store.createOrder({ customerName: customerName.trim() || "Khách hàng demo", customerEmail: email, productId: active.id, paymentMethod: "qr", paymentStatus: "pending" }); if (!order) { setCheckoutBusy(false); return; } try { const response = await fetch("/api/payments/checkout", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ productId: active.id, orderId: order.id, orderCode: order.orderCode, amount: order.total, currency: "VND", customerName: customerName.trim() || "Khách hàng demo", customerEmail: email, returnUrl: `${window.location.origin}/orders` }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Không thể tạo phiên thanh toán."); setPaymentMessage(result.checkoutUrl ? "Đã tạo checkout URL từ payment provider." : "Đã tạo QR/manual payment payload. Webhook sẽ cấp quyền sau khi thanh toán."); if (result.checkoutUrl) window.open(result.checkoutUrl, "_blank", "noopener,noreferrer"); setSuccessCode(result.orderCode || order.orderCode); setCheckoutId(null); setCustomerName(""); setCustomerEmail(""); } catch (error) { setPaymentMessage(error instanceof Error ? error.message : "Payment adapter gặp lỗi."); setSuccessCode(order.orderCode); setCheckoutId(null); } finally { setCheckoutBusy(false); } };
  const createProduct = () => { store.createProduct({ name: productName.trim() || "Sản phẩm mới", type: productType, referenceId: store.books[0]?.id ?? "manual", price: productPrice, status: "active", description: "Sản phẩm nội dung được tạo trực tiếp từ H2OBOOK Store." }); setProductName(""); setCreateOpen(false); };
  const scrollProducts = () => document.querySelector(".store-toolbar")?.scrollIntoView({ behavior: "smooth" });
  const revenue = store.products.reduce((sum, item) => sum + item.revenue, 0);
  return <AppShell>
    <div className="page-header"><div><span className="eyebrow">COMMERCE & LICENSING</span><h1>H2OBOOK Store</h1><p>Bán sách, template, quyền clone và membership trên cùng một storefront.</p></div><div className="header-actions"><button className="btn btn-secondary" onClick={() => window.open("/store?preview=public", "_blank")}><Eye size={16}/>Xem trang public</button><button className="btn btn-primary" onClick={() => setCreateOpen(true)}><Plus size={16}/>Tạo sản phẩm</button></div></div>
    <section className="store-summary"><div><ShoppingBag size={20}/><span><strong>{store.products.reduce((sum, item) => sum + item.sales, 0)}</strong>Lượt bán</span></div><div><CreditCard size={20}/><span><strong>{formatCurrency(revenue)}</strong>Doanh thu tích lũy</span></div><div><Users size={20}/><span><strong>{store.memberships.filter((item) => item.status === "active").length}</strong>Membership hoạt động</span></div><div><Copy size={20}/><span><strong>{store.clones.length}</strong>Quyền clone đã cấp</span></div></section>
    <section className="storefront-preview"><div className="storefront-copy"><Badge tone="purple"><Sparkles size={12}/>H2OBOOK KNOWLEDGE STORE</Badge><h2>Biến kiến thức chuyên môn thành tài sản có thể bán và cấp phép.</h2><p>Khách hàng mua sách, đối tác mua quyền clone, học viên đăng ký membership và nhận quyền truy cập tự động.</p><div><button className="btn btn-primary" onClick={scrollProducts}>Khám phá thư viện</button><button className="btn btn-secondary" onClick={() => { window.location.href = "/membership"; }}>Xem gói membership</button></div></div><div className="storefront-books">{store.products.slice(0, 3).map((product, index) => <div key={product.id} style={{ background: product.cover, transform: `rotate(${(index - 1) * 7}deg) translateY(${Math.abs(index - 1) * 18}px)` }}><small>H2OBOOK</small><strong>{product.name}</strong></div>)}</div></section>
    <div className="store-toolbar"><div className="search-box compact"><Search size={16}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Tìm sản phẩm..."/></div><div className="filter-tabs inline">{[["all","Tất cả"],["book","Sách"],["template","Template"],["membership","Membership"],["bundle","Combo"]].map(([value,label]) => <button className={type === value ? "active" : ""} key={value} onClick={() => setType(value)}>{label}</button>)}</div></div>
    <div className="product-grid">{products.map((product) => <article className="product-card" key={product.id}><div className="product-cover" style={{ background: product.cover }}><span>{product.type.toUpperCase()}</span><strong>{product.name}</strong></div><div className="product-body"><h3>{product.name}</h3><p>{product.description}</p><div className="product-price"><strong>{formatCurrency(product.price)}</strong>{product.compareAtPrice && <del>{formatCurrency(product.compareAtPrice)}</del>}{product.billingInterval && <span>/ {product.billingInterval === "month" ? "tháng" : "năm"}</span>}</div><div className="product-meta"><span>{product.sales} lượt bán</span><span>{formatCurrency(product.revenue)} doanh thu</span></div><button className="btn btn-primary" onClick={() => setCheckoutId(product.id)}><ShoppingBag size={15}/>Mua thử sản phẩm</button></div></article>)}</div>

    <Modal open={createOpen} onClose={() => setCreateOpen(false)} title="Tạo sản phẩm mới" description="Sản phẩm có thể liên kết với sách, template, membership hoặc combo."><div className="form-grid"><label className="field full"><span>Tên sản phẩm</span><input className="input" value={productName} onChange={(event) => setProductName(event.target.value)} placeholder="Giáo trình Makeup Cô Dâu"/></label><label className="field"><span>Loại sản phẩm</span><select className="select" value={productType} onChange={(event) => setProductType(event.target.value as typeof productType)}><option value="book">Sách</option><option value="template">Template</option><option value="membership">Membership</option><option value="bundle">Combo</option></select></label><label className="field"><span>Giá bán (₫)</span><input className="input" type="number" min="0" step="10000" value={productPrice} onChange={(event) => setProductPrice(Number(event.target.value))}/></label></div><div className="modal-actions"><button className="btn btn-secondary" onClick={() => setCreateOpen(false)}>Hủy</button><button className="btn btn-primary" onClick={createProduct}><Plus size={15}/>Tạo và mở bán</button></div></Modal>
    <Modal open={Boolean(active)} onClose={() => setCheckoutId(null)} title={`Thanh toán: ${active?.name ?? "Sản phẩm"}`} description="Luồng này gọi payment adapter thật khi đã cấu hình; Demo Mode dùng QR thủ công an toàn."><div className="checkout-summary"><div className="checkout-cover" style={{ background: active?.cover }}/><div><strong>{active?.name}</strong><span>{active?.description}</span><b>{formatCurrency(active?.price ?? 0)}</b></div></div><div className="form-grid"><label className="field"><span>Họ tên khách hàng</span><input className="input" value={customerName} onChange={(event) => setCustomerName(event.target.value)}/></label><label className="field"><span>Email nhận quyền</span><input className="input" value={customerEmail} onChange={(event) => setCustomerEmail(event.target.value)}/></label></div><div className="fake-qr-payment"><div className="fake-qr"><Store size={33}/></div><span><strong>Thanh toán QR</strong><small>Hệ thống sẽ tạo đơn chờ xác nhận và cấp quyền sau webhook.</small></span></div><div className="modal-actions"><button className="btn btn-secondary" onClick={() => setCheckoutId(null)}>Hủy</button><button className="btn btn-primary" disabled={checkoutBusy} onClick={checkout}><CreditCard size={15}/>{checkoutBusy ? "Đang tạo checkout..." : `Tạo đơn ${formatCurrency(active?.price ?? 0)}`}</button></div></Modal>
    <Modal open={Boolean(successCode)} onClose={() => setSuccessCode("")} title="Đơn hàng đã được tạo"><div className="success-state"><span><Check size={28}/></span><h3>{successCode}</h3><p>{paymentMessage || "Đơn hàng đang chờ thanh toán. Có thể kiểm tra và xác nhận tại trang Đơn hàng."}</p><button className="btn btn-primary" onClick={() => { window.location.href = "/orders"; }}>Mở danh sách đơn</button></div></Modal>
  </AppShell>;
}
