"use client";

import { useState } from "react";
import { AppShell } from "@/components/layout/app-shell";
import { Badge } from "@/components/ui/badge";
import { Modal } from "@/components/ui/modal";
import { useAppStore } from "@/store/app-store";
import { formatDate } from "@/lib/utils";
import { Activity, BellRing, CirclePlay, Pause, Plus, RotateCw, Webhook, Zap } from "lucide-react";
import type { AutomationAction, AutomationTrigger } from "@/types/domain";

const triggerLabels: Record<AutomationTrigger, string> = { "book.published": "Sách được xuất bản", "review.approved": "Bản duyệt được phê duyệt", "order.paid": "Đơn hàng thanh toán", "membership.expiring": "Membership sắp hết hạn", "student.inactive": "Học viên ngừng hoạt động", "clone.update_available": "Clone có bản cập nhật" };
const actionLabels: Record<AutomationAction, string> = { send_notification: "Gửi thông báo", grant_access: "Cấp quyền truy cập", create_review: "Tạo yêu cầu duyệt", sync_clone: "Đồng bộ clone", send_webhook: "Gửi webhook", create_task: "Tạo nhiệm vụ" };

export default function AutomationsPage() {
  const store = useAppStore(); const [open, setOpen] = useState(false); const [name, setName] = useState(""); const [trigger, setTrigger] = useState<AutomationTrigger>("book.published"); const [actions, setActions] = useState<AutomationAction[]>(["send_notification"]);
  const toggleAction = (action: AutomationAction) => setActions((current) => current.includes(action) ? current.filter((item) => item !== action) : [...current, action]);
  const create = () => { if (!name.trim() || !actions.length) return; store.createAutomation({ name: name.trim(), trigger, actions }); setOpen(false); setName(""); };
  return <AppShell>
    <div className="page-header"><div><span className="eyebrow">H2O AUTOMATION ENGINE</span><h1>Tự động hóa vận hành</h1><p>Kết nối sự kiện sách, đơn hàng, membership và clone thành quy trình tự chạy.</p></div><div className="header-actions"><button className="btn btn-primary" onClick={() => setOpen(true)}><Plus size={16}/>Tạo automation</button></div></div>
    <div className="automation-metrics"><div><Zap/><span><strong>{store.automations.filter((item) => item.status === "active").length}</strong><small>Đang hoạt động</small></span></div><div><RotateCw/><span><strong>{store.automations.reduce((sum, item) => sum + item.runCount, 0)}</strong><small>Lượt chạy</small></span></div><div><Activity/><span><strong>{store.automations.reduce((sum, item) => sum + item.errorCount, 0)}</strong><small>Lỗi đã ghi nhận</small></span></div><div><Webhook/><span><strong>{store.automations.filter((item) => item.actions.includes("send_webhook")).length}</strong><small>Kết nối webhook</small></span></div></div>
    <section className="section-card"><div className="section-head"><div><h2>Workflow đang cấu hình</h2><p>Mỗi rule gồm một trigger và một hoặc nhiều hành động.</p></div></div><div className="section-body automation-list">{store.automations.map((rule) => <article key={rule.id}><div className="automation-status"><span className={rule.status}/><Badge tone={rule.status === "active" ? "success" : "neutral"}>{rule.status === "active" ? "Đang bật" : "Tạm dừng"}</Badge></div><div className="automation-main"><strong>{rule.name}</strong><p><BellRing size={13}/>{triggerLabels[rule.trigger]}</p><div>{rule.actions.map((action) => <span key={action}>{actionLabels[action]}</span>)}</div></div><div className="automation-stats"><strong>{rule.runCount}</strong><small>lượt chạy</small><span>{rule.lastRunAt ? formatDate(rule.lastRunAt) : "Chưa chạy"}</span></div><div className="row-actions"><button className="btn btn-soft btn-sm" onClick={() => store.runAutomation(rule.id)}><CirclePlay size={13}/>Chạy thử</button><button className="btn btn-secondary btn-sm" onClick={() => store.toggleAutomation(rule.id)}>{rule.status === "active" ? <Pause size={13}/> : <Zap size={13}/>} {rule.status === "active" ? "Tạm dừng" : "Kích hoạt"}</button></div></article>)}</div></section>
    <Modal open={open} onClose={() => setOpen(false)} title="Tạo automation" description="Thiết lập sự kiện kích hoạt và các hành động liên tiếp."><div className="form-grid"><label className="field full"><span>Tên workflow</span><input className="input" value={name} onChange={(event) => setName(event.target.value)} placeholder="Ví dụ: Phê duyệt xong → xuất bản và thông báo"/></label><label className="field full"><span>Sự kiện kích hoạt</span><select className="select" value={trigger} onChange={(event) => setTrigger(event.target.value as AutomationTrigger)}>{Object.entries(triggerLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><div className="field full"><span>Hành động</span><div className="action-picker">{Object.entries(actionLabels).map(([value, label]) => <button className={actions.includes(value as AutomationAction) ? "active" : ""} key={value} onClick={() => toggleAction(value as AutomationAction)}>{label}</button>)}</div></div></div><div className="modal-actions"><button className="btn btn-secondary" onClick={() => setOpen(false)}>Hủy</button><button className="btn btn-primary" onClick={create}><Zap size={14}/>Lưu và kích hoạt</button></div></Modal>
  </AppShell>;
}
