"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowRight, BookOpen, Bot, CheckCircle2, ChevronRight, CirclePlay, Clock3, Compass, Flame, GraduationCap, Sparkles, Target, Trophy } from "lucide-react";
import { useAppStore } from "@/store/app-store";
import { studentAchievements, studentMissions, studentSkills } from "@/lib/student/experience";
import { SmartHomeRoadmapWidget } from "@/components/student/smart-home-roadmap-widget";

type LiveTask={id:string;title:string;description:string;href:string;estimatedMinutes:number};
type LiveSkill={key:string;label:string;masteryPercent:number;nextAction?:string};
type LiveSummary={user:{name:string;email:string};courseProgress:number;mastery:number;activeCourses:number;completedLessons:number;totalLessons:number;nextCourse:{slug:string;title:string}|null;skillMastery:LiveSkill[];todayTasks:LiveTask[];mode:"demo"|"production"};
export default function StudentDashboard(){const store=useAppStore();const student=store.students.find(item=>item.status==="active")??store.students[0];const [live,setLive]=useState<LiveSummary|null>(null);useEffect(()=>{fetch("/api/student/summary",{cache:"no-store"}).then(response=>response.ok?response.json():null).then(payload=>payload&&setLive(payload)).catch(()=>null)},[]);const activeMission=studentMissions[0];const liveTask=live?.mode==="production"?live.todayTasks?.[0]:undefined;const liveSkills=live?.mode==="production"&&live.skillMastery?.length?live.skillMastery:undefined;const skillMapStatus=(percent:number):"completed"|"active"|"locked"=>percent>=100?"completed":percent>0?"active":"locked";const skillMapItems=liveSkills?liveSkills.map(s=>({id:s.key,title:s.label,group:"Skill Mastery",progress:s.masteryPercent,status:skillMapStatus(s.masteryPercent),evidence:s.nextAction??""})):studentSkills.slice(0,7);const displayName=live?.user.name??student?.name??"bạn";const mastery=live?.mastery??student?.progress??68;return <>
  <section className="h2o-student-hero"><div><span className="h2o-student-eyebrow"><Sparkles/>AI LEARNING COMMAND CENTER</span><h1>Chào buổi sáng, {displayName.split(" ").slice(-1)[0]} 👋</h1><p>{live&&live.mode==="production"?`Bạn đã hoàn thành ${live.completedLessons}/${live.totalLessons} bài trong ${live.activeCourses} khóa đang mở.`:"Hôm nay bạn đang ở ngày thứ 18 trong hành trình trở thành Makeup Artist chuyên nghiệp."}</p><div><Link href={live?.nextCourse?`/student/courses/${live.nextCourse.slug}`:"/student/courses"} className="h2o-student-primary"><CirclePlay/>Tiếp tục bài đang học</Link><Link href="/student/roadmap" className="h2o-student-secondary"><Compass/>Xem lộ trình của tôi</Link></div></div><aside><div className="h2o-student-orb"><span>H₂</span><i/><i/><i/></div><div><small>MASTERY SCORE</small><strong>{mastery}%</strong><span><i style={{width:`${mastery}%`}}/></span><p>Skill Map cập nhật theo bài học đã hoàn thành</p></div></aside></section>

  <section className="h2o-student-metrics"><article><span><Flame/></span><div><strong>7 ngày</strong><small>Chuỗi học liên tục</small></div></article><article><span><Clock3/></span><div><strong>42 giờ</strong><small>Thời gian thực hành</small></div></article><article><span><Target/></span><div><strong>6/9</strong><small>Kỹ năng đang mở</small></div></article><article><span><Trophy/></span><div><strong>4</strong><small>Thành tựu đã đạt</small></div></article></section>

  <div className="h2o-student-dashboard-grid">
    {liveTask?<section className="h2o-student-card h2o-today-mission"><header><div><span>NHIỆM VỤ HÔM NAY</span><h2>{liveTask.title}</h2><p>{liveTask.description}</p></div><small><Clock3/>{liveTask.estimatedMinutes} phút</small></header><footer><Link href={liveTask.href}>Bắt đầu <ArrowRight/></Link></footer></section>:
    <section className="h2o-student-card h2o-today-mission"><header><div><span>NHIỆM VỤ HÔM NAY</span><h2>{activeMission.title}</h2><p>{activeMission.detail}</p></div><small><Clock3/>{activeMission.duration}</small></header><div className="h2o-mission-progress"><span><i style={{width:`${activeMission.progress}%`}}/></span><b>{activeMission.progress}%</b></div><div className="h2o-mission-steps">{activeMission.steps.map((step,index)=><div key={step} className={index<2?"done":""}><span>{index<2?<CheckCircle2/>:index+1}</span><strong>{step}</strong></div>)}</div><footer><Link href="/reader/book_skin">Tiếp tục nhiệm vụ <ArrowRight/></Link><span>Hoàn thành trước 21:00</span></footer></section>}

    <section className="h2o-student-card h2o-mentor-card"><div className="h2o-mentor-card-aura"/><header><Bot/><span><small>H2O MENTOR</small><strong>Trợ lý học tập của bạn</strong></span><i>LOCAL</i></header><blockquote>“Bạn đang tiến bộ tốt ở kỹ thuật nền. Hôm nay nên tập trung vào độ mỏng vùng má và thời gian chờ giữa các lớp.”</blockquote><div className="h2o-mentor-suggestions"><Link href="/student/mentor">Tôi nên học bài nào tiếp?</Link><Link href="/student/mentor">Bài tập của tôi còn thiếu gì?</Link></div><Link href="/student/mentor" className="h2o-mentor-open">Mở H2O Mentor <ArrowRight/></Link></section>
  </div>

  <div className="h2o-student-dashboard-grid second">
    <section className="h2o-student-card"><header className="h2o-student-card-head"><div><span>CONTINUE LEARNING</span><h2>Tiếp tục học</h2></div><Link href="/student/courses">Tất cả <ArrowRight/></Link></header><div className="h2o-student-continue-list">{store.books.slice(0,3).map((book,index)=><Link key={book.id} href={`/reader/${book.id}`}><div style={{background:book.cover}}><small>0{index+1}</small><BookOpen/></div><span><small>{index===0?"BÀI ĐANG HỌC":"SÁCH GỢI Ý"}</small><strong>{book.title}</strong><p>{index===0?"Bài 3.2 · Kỹ thuật nền cô dâu":book.subtitle}</p><em><i style={{width:`${62-index*14}%`}}/></em></span><ChevronRight/></Link>)}</div></section>
    <SmartHomeRoadmapWidget mastery={mastery}/>
  </div>

  <section className="h2o-student-card h2o-skill-map-preview"><header className="h2o-student-card-head"><div><span>SKILL MAP</span><h2>Bản đồ kỹ năng của bạn</h2><p>Mỗi kỹ năng được mở bằng bài học, thực hành và bằng chứng năng lực.</p></div><Link href="/student/roadmap">Xem toàn bộ <ArrowRight/></Link></header><div className="h2o-skill-map-row">{skillMapItems.map((skill,index)=><article key={skill.id} className={skill.status}><div><span>{skill.progress}%</span><i style={{"--skill-progress":`${skill.progress*3.6}deg`} as React.CSSProperties}/></div><small>{skill.group}</small><strong>{skill.title}</strong><p>{skill.evidence}</p>{index<6&&<ArrowRight className="connector"/>}</article>)}</div></section>

  <div className="h2o-student-dashboard-grid third"><section className="h2o-student-card"><header className="h2o-student-card-head"><div><span>UPCOMING ASSIGNMENTS</span><h2>Bài tập cần hoàn thành</h2></div><Link href="/student/assignments">Xem tất cả <ArrowRight/></Link></header><div className="h2o-student-assignment-list">{store.assignments.slice(0,3).map((assignment,index)=><article key={assignment.id}><span className={index===0?"urgent":""}>{index===0?"Còn 2 ngày":"Tuần này"}</span><div><strong>{assignment.title}</strong><p>{assignment.instructions}</p><small>{assignment.maxScore} điểm · Cần tải ảnh bài làm</small></div><Link href="/student/assignments"><ArrowRight/></Link></article>)}</div></section><section className="h2o-student-card"><header className="h2o-student-card-head"><div><span>ACHIEVEMENTS</span><h2>Thành tựu mới nhất</h2></div><Link href="/student/profile">Hồ sơ <ArrowRight/></Link></header><div className="h2o-achievement-grid">{studentAchievements.map(item=><article key={item.title}><span>{item.icon}</span><strong>{item.title}</strong><small>{item.description}</small></article>)}</div></section></div>
</>}
