"use client";
import Link from "next/link";
import { ArrowRight, BookOpen, Bot, CheckCircle2, ChevronRight, CirclePlay, Clock3, Compass, Flame, GraduationCap, Sparkles, Target, Trophy } from "lucide-react";
import { useAppStore } from "@/store/app-store";
import { studentAchievements, studentCareerStages, studentMissions, studentSkills } from "@/lib/student/experience";

export default function StudentDashboard(){const store=useAppStore();const student=store.students.find(item=>item.status==="active")??store.students[0];const activeMission=studentMissions[0];const currentStage=studentCareerStages.find(item=>item.status==="active");return <>
  <section className="h2o-student-hero"><div><span className="h2o-student-eyebrow"><Sparkles/>AI LEARNING COMMAND CENTER</span><h1>Chào buổi sáng, {student?.name?.split(" ").slice(-1)[0] ?? "bạn"} 👋</h1><p>Hôm nay bạn đang ở ngày thứ 18 trong hành trình trở thành Makeup Artist chuyên nghiệp.</p><div><Link href="/student/courses" className="h2o-student-primary"><CirclePlay/>Tiếp tục bài đang học</Link><Link href="/student/roadmap" className="h2o-student-secondary"><Compass/>Xem lộ trình của tôi</Link></div></div><aside><div className="h2o-student-orb"><span>H₂</span><i/><i/><i/></div><div><small>MASTERY SCORE</small><strong>{student?.progress ?? 68}%</strong><span><i style={{width:`${student?.progress ?? 68}%`}}/></span><p>Đang tiến đúng nhịp · 3 kỹ năng cần luyện thêm</p></div></aside></section>

  <section className="h2o-student-metrics"><article><span><Flame/></span><div><strong>7 ngày</strong><small>Chuỗi học liên tục</small></div></article><article><span><Clock3/></span><div><strong>42 giờ</strong><small>Thời gian thực hành</small></div></article><article><span><Target/></span><div><strong>6/9</strong><small>Kỹ năng đang mở</small></div></article><article><span><Trophy/></span><div><strong>4</strong><small>Thành tựu đã đạt</small></div></article></section>

  <div className="h2o-student-dashboard-grid">
    <section className="h2o-student-card h2o-today-mission"><header><div><span>NHIỆM VỤ HÔM NAY</span><h2>{activeMission.title}</h2><p>{activeMission.detail}</p></div><small><Clock3/>{activeMission.duration}</small></header><div className="h2o-mission-progress"><span><i style={{width:`${activeMission.progress}%`}}/></span><b>{activeMission.progress}%</b></div><div className="h2o-mission-steps">{activeMission.steps.map((step,index)=><div key={step} className={index<2?"done":""}><span>{index<2?<CheckCircle2/>:index+1}</span><strong>{step}</strong></div>)}</div><footer><Link href="/reader/book_skin">Tiếp tục nhiệm vụ <ArrowRight/></Link><span>Hoàn thành trước 21:00</span></footer></section>

    <section className="h2o-student-card h2o-mentor-card"><div className="h2o-mentor-card-aura"/><header><Bot/><span><small>H2O MENTOR</small><strong>Trợ lý học tập của bạn</strong></span><i>LOCAL</i></header><blockquote>“Bạn đang tiến bộ tốt ở kỹ thuật nền. Hôm nay nên tập trung vào độ mỏng vùng má và thời gian chờ giữa các lớp.”</blockquote><div className="h2o-mentor-suggestions"><Link href="/student/mentor">Tôi nên học bài nào tiếp?</Link><Link href="/student/mentor">Bài tập của tôi còn thiếu gì?</Link></div><Link href="/student/mentor" className="h2o-mentor-open">Mở H2O Mentor <ArrowRight/></Link></section>
  </div>

  <div className="h2o-student-dashboard-grid second">
    <section className="h2o-student-card"><header className="h2o-student-card-head"><div><span>CONTINUE LEARNING</span><h2>Tiếp tục học</h2></div><Link href="/student/courses">Tất cả <ArrowRight/></Link></header><div className="h2o-student-continue-list">{store.books.slice(0,3).map((book,index)=><Link key={book.id} href={`/reader/${book.id}`}><div style={{background:book.cover}}><small>0{index+1}</small><BookOpen/></div><span><small>{index===0?"BÀI ĐANG HỌC":"SÁCH GỢI Ý"}</small><strong>{book.title}</strong><p>{index===0?"Bài 3.2 · Kỹ thuật nền cô dâu":book.subtitle}</p><em><i style={{width:`${62-index*14}%`}}/></em></span><ChevronRight/></Link>)}</div></section>
    <section className="h2o-student-card"><header className="h2o-student-card-head"><div><span>CAREER MILESTONE</span><h2>Mốc nghề nghiệp hiện tại</h2></div><Link href="/student/roadmap">Bản đồ <ArrowRight/></Link></header><div className="h2o-current-stage"><Compass/><small>GIAI ĐOẠN HIỆN TẠI</small><h3>{currentStage?.title}</h3><p>{currentStage?.description}</p><div>{currentStage?.requirements.map((item,index)=><span key={item} className={index===0?"done":""}>{index===0?<CheckCircle2/>:<i/>}{item}</span>)}</div><strong>Mốc tiếp theo: Makeup Artist có khách đầu tiên</strong></div></section>
  </div>

  <section className="h2o-student-card h2o-skill-map-preview"><header className="h2o-student-card-head"><div><span>SKILL MAP</span><h2>Bản đồ kỹ năng của bạn</h2><p>Mỗi kỹ năng được mở bằng bài học, thực hành và bằng chứng năng lực.</p></div><Link href="/student/roadmap">Xem toàn bộ <ArrowRight/></Link></header><div className="h2o-skill-map-row">{studentSkills.slice(0,7).map((skill,index)=><article key={skill.id} className={skill.status}><div><span>{skill.progress}%</span><i style={{"--skill-progress":`${skill.progress*3.6}deg`} as React.CSSProperties}/></div><small>{skill.group}</small><strong>{skill.title}</strong><p>{skill.evidence}</p>{index<6&&<ArrowRight className="connector"/>}</article>)}</div></section>

  <div className="h2o-student-dashboard-grid third"><section className="h2o-student-card"><header className="h2o-student-card-head"><div><span>UPCOMING ASSIGNMENTS</span><h2>Bài tập cần hoàn thành</h2></div><Link href="/student/assignments">Xem tất cả <ArrowRight/></Link></header><div className="h2o-student-assignment-list">{store.assignments.slice(0,3).map((assignment,index)=><article key={assignment.id}><span className={index===0?"urgent":""}>{index===0?"Còn 2 ngày":"Tuần này"}</span><div><strong>{assignment.title}</strong><p>{assignment.instructions}</p><small>{assignment.maxScore} điểm · Cần tải ảnh bài làm</small></div><Link href="/student/assignments"><ArrowRight/></Link></article>)}</div></section><section className="h2o-student-card"><header className="h2o-student-card-head"><div><span>ACHIEVEMENTS</span><h2>Thành tựu mới nhất</h2></div><Link href="/student/profile">Hồ sơ <ArrowRight/></Link></header><div className="h2o-achievement-grid">{studentAchievements.map(item=><article key={item.title}><span>{item.icon}</span><strong>{item.title}</strong><small>{item.description}</small></article>)}</div></section></div>
</>}
