"use client";

import { useState } from "react";
import { AppShell } from "@/components/layout/app-shell";
import { Badge } from "@/components/ui/badge";
import { Modal } from "@/components/ui/modal";
import { useAppStore } from "@/store/app-store";
import { formatCurrency, formatDate } from "@/lib/utils";
import { BadgeDollarSign, Building2, CheckCircle2, FileSignature, Plus, ReceiptText, Users } from "lucide-react";
import type { LicenseAgreement } from "@/types/domain";

export default function LicensingPage() {
  const store = useAppStore(); const [open, setOpen] = useState(false); const [licensee, setLicensee] = useState(""); const [templateId, setTemplateId] = useState(store.templates[0]?.id ?? ""); const [model, setModel] = useState<LicenseAgreement["model"]>("subscription"); const [price, setPrice] = useState(1290000);
  const activeRevenue = store.licenses.reduce((sum, item) => sum + item.revenue, 0); const pendingRoyalty = store.royaltyPayouts.filter((item) => item.status !== "paid").reduce((sum, item) => sum + item.amount, 0);
  const create = () => { if (!licensee.trim() || !templateId) return; store.createLicense({ templateId, licenseeName: licensee.trim(), model, price, revenueSharePercent: model === "revenue_share" ? 20 : 0, status: "active", seats: 50, cloneLimit: 3 }); setOpen(false); setLicensee(""); };
  return <AppShell>
    <div className="page-header"><div><span className="eyebrow">CONTENT LICENSING & ROYALTY</span><h1>Cấp phép và chia sẻ doanh thu</h1><p>Quản lý quyền sử dụng template, giới hạn clone, số ghế và royalty cho đối tác.</p></div><div className="header-actions"><button className="btn btn-primary" onClick={() => setOpen(true)}><Plus size={16}/>Tạo hợp đồng</button></div></div>
    <div className="license-metrics"><div><FileSignature/><span><strong>{store.licenses.filter((item) => item.status === "active").length}</strong><small>Hợp đồng hoạt động</small></span></div><div><Building2/><span><strong>{new Set(store.licenses.map((item) => item.licenseeName)).size}</strong><small>Đối tác được cấp phép</small></span></div><div><BadgeDollarSign/><span><strong>{formatCurrency(activeRevenue)}</strong><small>Doanh thu ghi nhận</small></span></div><div><ReceiptText/><span><strong>{formatCurrency(pendingRoyalty)}</strong><small>Royalty chờ xử lý</small></span></div></div>
    <div className="licensing-grid"><section className="section-card"><div className="section-head"><div><h2>Hợp đồng nội dung</h2><p>Quyền clone và phân phối theo từng đối tác.</p></div></div><div className="section-body license-list">{store.licenses.map((license) => { const template = store.templates.find((item) => item.id === license.templateId); return <article key={license.id}><div className="license-icon"><FileSignature size={18}/></div><div className="license-main"><div><strong>{license.licenseeName}</strong><Badge tone={license.status === "active" ? "success" : "warning"}>{license.status}</Badge></div><p>{template?.name ?? license.templateId}</p><div><span>{license.model === "revenue_share" ? `${license.revenueSharePercent}% chia sẻ` : formatCurrency(license.price)}</span><span><Users size={12}/>{license.seats} ghế</span><span>{license.clonesUsed}/{license.cloneLimit} clone</span></div></div><div className="license-revenue"><strong>{formatCurrency(license.revenue)}</strong><small>Từ {formatDate(license.startsAt)}</small><button onClick={() => store.updateLicenseStatus(license.id, license.status === "active" ? "suspended" : "active")}>{license.status === "active" ? "Tạm ngưng" : "Kích hoạt"}</button></div></article>; })}</div></section><section className="section-card"><div className="section-head"><div><h2>Royalty payout</h2><p>Đối soát doanh thu chia sẻ.</p></div></div><div className="section-body payout-list">{store.royaltyPayouts.map((payout) => <article key={payout.id}><div><strong>{payout.period}</strong><small>{payout.payeeName}</small></div><div><span>Doanh thu gộp</span><strong>{formatCurrency(payout.grossRevenue)}</strong></div><div><span>Tỷ lệ</span><strong>{payout.rate}%</strong></div><div><span>Thanh toán</span><strong>{formatCurrency(payout.amount)}</strong></div><button className="btn btn-sm btn-secondary" onClick={() => store.approveRoyaltyPayout(payout.id)} disabled={payout.status === "paid"}>{payout.status === "pending" ? "Duyệt" : payout.status === "approved" ? "Đánh dấu đã trả" : <><CheckCircle2 size={13}/>Đã trả</>}</button></article>)}</div></section></div>
    <Modal open={open} onClose={() => setOpen(false)} title="Tạo hợp đồng cấp phép" description="Cấp quyền sử dụng template cho học viện hoặc thương hiệu đối tác."><div className="form-grid"><label className="field full"><span>Tên đối tác</span><input className="input" value={licensee} onChange={(event) => setLicensee(event.target.value)} placeholder="Tên học viện hoặc thương hiệu"/></label><label className="field"><span>Template</span><select className="select" value={templateId} onChange={(event) => setTemplateId(event.target.value)}>{store.templates.map((template) => <option key={template.id} value={template.id}>{template.name}</option>)}</select></label><label className="field"><span>Mô hình</span><select className="select" value={model} onChange={(event) => setModel(event.target.value as LicenseAgreement["model"])}><option value="one_time">Mua một lần</option><option value="subscription">Thuê bao</option><option value="revenue_share">Chia sẻ doanh thu</option></select></label><label className="field full"><span>Giá hợp đồng</span><input className="input" type="number" value={price} onChange={(event) => setPrice(Number(event.target.value))}/></label></div><div className="modal-actions"><button className="btn btn-secondary" onClick={() => setOpen(false)}>Hủy</button><button className="btn btn-primary" onClick={create}><FileSignature size={14}/>Tạo hợp đồng</button></div></Modal>
  </AppShell>;
}
