"use client";

import { useState } from "react";
import Link from "next/link";
import { AppShell } from "@/components/layout/app-shell";
import { Badge } from "@/components/ui/badge";
import { Modal } from "@/components/ui/modal";
import { useAppStore } from "@/store/app-store";
import { formatDate } from "@/lib/utils";
import { BookOpen, CheckCircle2, Globe2, MonitorSmartphone, Palette, Plus, Settings2, UsersRound } from "lucide-react";

export default function WhiteLabelPage() {
  const store = useAppStore(); const [open, setOpen] = useState(false); const [name, setName] = useState(""); const [domain, setDomain] = useState("");
  const create = () => { if (!name.trim()) return; store.createWhiteLabelPortal({ name: name.trim(), customDomain: domain.trim() || undefined, bookIds: store.books.slice(0, 2).map((book) => book.id) }); setOpen(false); setName(""); setDomain(""); };
  return <AppShell>
    <div className="page-header"><div><span className="eyebrow">WHITE-LABEL LEARNING PORTALS</span><h1>Cổng thư viện thương hiệu riêng</h1><p>Tạo website đọc sách cho từng học viện với domain, logo, màu sắc và thư viện riêng.</p></div><div className="header-actions"><button className="btn btn-primary" onClick={() => setOpen(true)}><Plus size={16}/>Tạo portal</button></div></div>
    <div className="portal-grid">{store.whiteLabelPortals.map((portal) => <article className="portal-card" key={portal.id}><div className="portal-preview" style={{ "--portal-primary": portal.primaryColor, "--portal-accent": portal.accentColor } as React.CSSProperties}><header><span className="portal-logo">H2</span><strong>{portal.name}</strong><nav><i/><i/><i/></nav></header><div><small>THƯ VIỆN ĐÀO TẠO</small><h2>Kiến thức của bạn,<br/>thương hiệu của bạn.</h2><span className="portal-cta">Khám phá thư viện</span></div><footer>{portal.bookIds.slice(0, 3).map((id) => <span key={id}/>)}</footer></div><div className="portal-body"><div className="portal-title"><div><strong>{portal.name}</strong><span>{portal.customDomain ?? `/${portal.slug}`}</span></div><Badge tone={portal.status === "active" ? "success" : "warning"}>{portal.status}</Badge></div><div className="portal-stats"><span><BookOpen size={14}/><strong>{portal.bookIds.length}</strong><small>Sách</small></span><span><UsersRound size={14}/><strong>{portal.memberCount}</strong><small>Thành viên</small></span><span><Globe2 size={14}/><strong>{portal.plan}</strong><small>Gói</small></span></div><div className="portal-meta"><span><Palette size={13}/><i style={{ background: portal.primaryColor }}/><i style={{ background: portal.accentColor }}/></span><span>Cập nhật {formatDate(portal.updatedAt)}</span></div><div className="portal-actions"><Link className="btn btn-soft btn-sm" href={`/portal/${portal.slug}`}><Globe2 size={13}/>Xem portal</Link><button className="btn btn-secondary btn-sm" onClick={() => store.updateWhiteLabelPortal(portal.id, { theme: portal.theme === "dark" ? "light" : "dark" })}><MonitorSmartphone size={13}/>Đổi theme</button><button className="btn btn-primary btn-sm" onClick={() => store.updateWhiteLabelPortal(portal.id, { status: portal.status === "active" ? "maintenance" : "active" })}>{portal.status === "active" ? <Settings2 size={13}/> : <CheckCircle2 size={13}/>} {portal.status === "active" ? "Bảo trì" : "Kích hoạt"}</button></div></div></article>)}</div>
    <Modal open={open} onClose={() => setOpen(false)} title="Tạo white-label portal" description="Portal dùng chung dữ liệu sách và membership của H2OBOOK."><div className="form-grid"><label className="field full"><span>Tên portal</span><input className="input" value={name} onChange={(event) => setName(event.target.value)} placeholder="Ví dụ: H2O Makeup Academy Library"/></label><label className="field full"><span>Custom domain</span><input className="input" value={domain} onChange={(event) => setDomain(event.target.value)} placeholder="book.ten-thuong-hieu.vn"/></label></div><div className="modal-actions"><button className="btn btn-secondary" onClick={() => setOpen(false)}>Hủy</button><button className="btn btn-primary" onClick={create}><Globe2 size={14}/>Tạo portal</button></div></Modal>
  </AppShell>;
}
