"use client";
import { useState } from "react";
import { Building2, KeyRound, Plus, ShieldCheck, Webhook } from "lucide-react";
import { emitSystemEvent } from "@/lib/system-governance-ops-v2/events";
import { Panel, SystemPageHeader } from "../system-shared";
import styles from "../system-governance-ops-v2.module.css";

export function EnterpriseV2() {
  const [keys, setKeys] = useState([{ id: "key-1", name: "Production Reader", prefix: "h2o_live_••••4f2a", scopes: "books:read analytics:write", createdAt: "28/07/2026" }]);
  const [hooks, setHooks] = useState([{ id: "hook-1", url: "https://example.com/h2obook/events", events: "order.paid, publication.created", status: "active" }]);
  return <>
    <SystemPageHeader eyebrow="ENTERPRISE CONTROL PLANE" title="Enterprise & API" description="Quản lý API key, webhook, tổ chức nhiều cấp, quota và chính sách dữ liệu." actions={<span className={styles.heroPill}><ShieldCheck/>Tenant isolated</span>}/>
    <div className={styles.twoColumn}><Panel title="API Keys" description="Raw secret chỉ hiển thị một lần và DB chỉ lưu SHA-256." icon={<KeyRound/>}><div className={styles.panelActions}><button className={styles.primaryButton} onClick={() => { setKeys((current) => [...current, { id: crypto.randomUUID(), name: "New API Key", prefix: "h2o_live_••••new", scopes: "books:read", createdAt: "31/07/2026" }]); emitSystemEvent("system_action_clicked", { surface: "enterprise", action: "create_api_key" }); }}><Plus/>Tạo API key</button></div><div className={styles.listRows}>{keys.map((key) => <div key={key.id}><KeyRound/><span><strong>{key.name}</strong><small>{key.prefix} · {key.scopes}</small></span><button className={styles.softButton}>Thu hồi</button></div>)}</div></Panel><Panel title="Webhook" description="HMAC, retry, idempotency và dead-letter queue." icon={<Webhook/>}><div className={styles.panelActions}><button className={styles.primaryButton} onClick={() => setHooks((current) => [...current, { id: crypto.randomUUID(), url: "https://example.com/new-hook", events: "order.paid", status: "draft" }])}><Plus/>Tạo webhook</button></div><div className={styles.listRows}>{hooks.map((hook) => <div key={hook.id}><Webhook/><span><strong>{hook.url}</strong><small>{hook.events} · {hook.status}</small></span><button className={styles.softButton}>Kiểm tra</button></div>)}</div></Panel></div>
    <div className={styles.twoColumn}><Panel title="Organization" description="Đơn vị, chi nhánh, đội nhóm và cấu hình SSO." icon={<Building2/>}><div className={styles.listRows}><div><Building2/><span><strong>Organization Units</strong><small>Học viện · chi nhánh · đội nhóm</small></span><button className={styles.softButton}>Quản lý</button></div><div><KeyRound/><span><strong>SSO Configuration</strong><small>SAML/OIDC metadata foundation</small></span><button className={styles.softButton}>Cấu hình</button></div><div><ShieldCheck/><span><strong>Data Retention</strong><small>Policy xóa, lưu trữ và legal hold</small></span><button className={styles.softButton}>Mở policy</button></div></div></Panel><Panel title="Usage Quota" description="Giới hạn theo gói và cảnh báo sớm."><div className={styles.quotaList}><div><span>Dung lượng<small>1.8 / 25 GB</small></span><i><b style={{ width: "7%" }}/></i><em>ok</em></div><div><span>API tháng<small>0 / 100.000 request</small></span><i><b style={{ width: "1%" }}/></i><em>ok</em></div><div><span>Seats<small>1 / 25 tài khoản</small></span><i><b style={{ width: "4%" }}/></i><em>ok</em></div></div></Panel></div>
  </>;
}
