"use client";
import { Database, HardDrive, Save, ShieldCheck } from "lucide-react";
import { emitSystemEvent } from "@/lib/system-governance-ops-v2/events";
import { Panel, SystemPageHeader } from "../system-shared";
import styles from "../system-governance-ops-v2.module.css";

export function SettingsV2() {
  return <>
    <SystemPageHeader eyebrow="WORKSPACE CONFIGURATION" title="Cài đặt hệ thống" description="Cấu hình workspace, hạ tầng, bảo mật, domain và sao lưu dữ liệu." actions={<button className={styles.primaryButton} onClick={() => emitSystemEvent("system_policy_saved", { surface: "settings", target: "workspace" })}><Save/>Lưu thay đổi</button>}/>
    <Panel title="Thông tin workspace" description="Hiển thị trong dashboard, hóa đơn và storefront."><div className={styles.formGrid}><label>Tên workspace<input defaultValue="THUYH2O Makeup Academy"/></label><label>Slug<input defaultValue="thuyh2o-academy"/></label><label>Chủ sở hữu<input defaultValue="Thủy H2O"/></label><label>Email quản trị<input defaultValue="hello@thuyh2o.vn"/></label><label>Điện thoại<input defaultValue="0900 000 000"/></label><label>Màu hệ thống<input type="color" defaultValue="#6f1d46"/></label><label className={styles.fullField}>Tên miền riêng<input defaultValue="books.tenhocvien.vn"/></label></div></Panel>
    <div className={styles.twoColumn}><Panel title="Dung lượng" description="Cloud storage usage." icon={<HardDrive/>}><div className={styles.storageScore}><strong>1.8 GB</strong><span>/ 25 GB</span><i><b style={{ width: "7%" }}/></i><small>Ảnh, PDF, video, audio và file export.</small></div></Panel><Panel title="Sao lưu" description="Local-first data package." icon={<Database/>}><div className={styles.stackActions}><button className={styles.secondaryButton}>Tải backup V4</button><button className={styles.secondaryButton}>Khôi phục backup</button><button className={styles.dangerButton}>Reset dữ liệu demo</button></div></Panel></div>
    <Panel title="Kết nối production" description="Tên biến môi trường cần thiết, không hiển thị giá trị."><div className={styles.envGrid}>{[{ title: "Supabase", vars: ["NEXT_PUBLIC_SUPABASE_URL","NEXT_PUBLIC_SUPABASE_ANON_KEY","SUPABASE_SERVICE_ROLE_KEY"] },{ title: "Cloudflare R2", vars: ["R2_ACCOUNT_ID","R2_ACCESS_KEY_ID","R2_SECRET_ACCESS_KEY","R2_BUCKET"] },{ title: "Payment Provider", vars: ["PAYMENT_PROVIDER","PAYMENT_WEBHOOK_SECRET"] },{ title: "Security & Monitoring", vars: ["SENTRY_DSN","CRON_SECRET","ENCRYPTION_KEY"] }].map((group) => <article key={group.title}><strong>{group.title}</strong>{group.vars.map((variable) => <code key={variable}>{variable}</code>)}</article>)}</div></Panel>
    <Panel title="Chính sách bảo mật" description="Các nguyên tắc bắt buộc của H2OBOOK." icon={<ShieldCheck/>}><div className={styles.checkGrid}>{["Bật RLS trên toàn bộ bảng dữ liệu workspace","Không dùng service role key trên trình duyệt","Tài sản private chỉ mở qua signed URL","Webhook xác minh chữ ký trước khi cấp entitlement","Kiểm tra MIME thực tế và giới hạn dung lượng","Ghi audit log cho publish, clone, payment và role"].map((item) => <div key={item}><ShieldCheck/><span>{item}</span></div>)}</div></Panel>
  </>;
}
