"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { BookOpen, Eye, EyeOff, LoaderCircle, ShieldCheck } from "lucide-react";
import { createSupabaseBrowserClient } from "@/lib/supabase/client";
import { GoogleGlyph } from "./google-glyph";

/** Pre-Auth-Experience-V2 login form. Kept intact so NEXT_PUBLIC_AUTH_EXPERIENCE_V2=false restores it verbatim. */
export function LegacyLoginForm() {
  const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [show,setShow]=useState(false); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [googleLoading,setGoogleLoading]=useState(false);
  const submitWithGoogle=async()=>{ setGoogleLoading(true); setError(""); const supabase=createSupabaseBrowserClient(); if(!supabase){ setError("Hệ thống đăng nhập chưa được cấu hình."); setGoogleLoading(false); return; } const next=new URLSearchParams(window.location.search).get("next"); const safeNext=next?.startsWith("/")&&!next.startsWith("//")?next:null; const {error:authError}=await supabase.auth.signInWithOAuth({provider:"google",options:{redirectTo:`${window.location.origin}/auth/callback${safeNext?`?next=${encodeURIComponent(safeNext)}`:""}`}}); if(authError){setError(authError.message);setGoogleLoading(false);} };
  // §4.2: surface the auth callback's expired/invalid-link redirect instead of a silent failure.
  useEffect(()=>{ if(new URLSearchParams(window.location.search).get("error")==="link_expired") setError("Đường dẫn đăng nhập đã hết hạn hoặc đã được dùng. Vui lòng đăng nhập lại hoặc yêu cầu email mới."); },[]);
  const submit=async(event:FormEvent)=>{ event.preventDefault(); setLoading(true); setError(""); const supabase=createSupabaseBrowserClient(); if(!supabase){ window.location.href="/dashboard"; return; } const {error:authError}=await supabase.auth.signInWithPassword({email,password}); if(authError){setError(authError.message);setLoading(false);return;} await fetch("/api/auth/claim-access",{method:"POST"}).catch(()=>null);
    // Safety net for self-registered accounts stuck in limbo (see public-login-experience.tsx's
    // matching comment) — getCurrentUser() defaults to role "student" whenever there is no real
    // organization_members row yet, so this only fires for real students or that exact limbo case.
    const sessionResponse=await fetch("/api/auth/session").catch(()=>null);const sessionPayload=sessionResponse?.ok?await sessionResponse.json().catch(()=>null):null;
    if(sessionPayload?.user?.role==="student") await fetch("/api/auth/register-student",{method:"POST"}).catch(()=>null);
    const next=new URLSearchParams(window.location.search).get("next");if(next?.startsWith("/")&&!next.startsWith("//")){window.location.href=next;return;}
    window.location.href=sessionPayload?.user?.role==="student"?"/student":"/dashboard"; };
  return <main className="auth-page"><section className="auth-brand"><div className="auth-brand-inner"><span className="auth-logo"><BookOpen/>H2OBOOK</span><h1>Hệ điều hành xuất bản và kinh doanh tri thức.</h1><p>Thiết kế sách, clone thương hiệu, đào tạo học viên và bán membership trong một nền tảng thống nhất.</p><div className="auth-trust"><ShieldCheck/><span><strong>Production-ready</strong><small>Auth, RLS, private storage và audit log.</small></span></div></div></section><section className="auth-panel"><form className="auth-card" onSubmit={submit}><span className="eyebrow">WELCOME BACK</span><h2>Đăng nhập H2OBOOK</h2><p>Truy cập workspace của anh và tiếp tục dự án.</p>{error&&<div className="auth-error">{error}</div>}<button type="button" className="btn btn-secondary auth-submit" onClick={submitWithGoogle} disabled={googleLoading} style={{marginBottom:16,display:"flex",alignItems:"center",justifyContent:"center",gap:8}}>{googleLoading?<LoaderCircle className="spin"/>:<GoogleGlyph/>}Đăng nhập bằng Google</button><div style={{display:"flex",alignItems:"center",gap:10,margin:"0 0 16px",color:"#9c8f97",fontSize:12}}><i style={{flex:1,height:1,background:"#e5dde1"}}/>hoặc dùng email<i style={{flex:1,height:1,background:"#e5dde1"}}/></div><label className="field"><span>Email</span><input className="input" type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label className="field"><span>Mật khẩu</span><div className="password-field"><input className="input" type={show?"text":"password"} required value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••"/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</button></div></label><div className="auth-row"><label><input type="checkbox"/> Ghi nhớ đăng nhập</label><Link href="/signup">Chưa có tài khoản?</Link></div><button className="btn btn-primary auth-submit" disabled={loading}>{loading?<LoaderCircle className="spin"/>:null}Đăng nhập</button><div className="auth-demo"><span>Chưa cấu hình Supabase?</span><Link href="/dashboard">Demo quản trị</Link><Link href="/student">Demo học viên</Link></div></form></section></main>;
}
