"use client";

import Link from "next/link";
import { ArrowRight, BellRing, BrainCircuit, CheckCheck, ClipboardCheck, FileWarning, GraduationCap, LifeBuoy, Workflow } from "lucide-react";
import { useState } from "react";
import { useOperationsStore } from "@/store/operations-store";
import { useAdmissionLeads } from "./use-admission-leads";
import { useApprovalRequests, useSubmissionQueue, useSupportTickets } from "./use-operations-data";
import { OperationsMetric } from "./metric-card";
import { StatusBadge } from "./status-badge";
import styles from "./operations.module.css";

export function OperationsDashboard() {
  const store = useOperationsStore();
  const [showBriefing, setShowBriefing] = useState(false);
  const admissions = useAdmissionLeads();
  const submissions = useSubmissionQueue();
  const tickets = useSupportTickets();
  const approvals = useApprovalRequests();
  const followUpLeads = admissions.leads.filter((lead) => lead.stage !== "enrolled" && lead.stage !== "lost").slice(0, 4);
  const pendingApprovals = approvals.rows.filter((item) => item.status === "pending");
  const openTickets = tickets.rows.filter((item) => !["resolved", "closed"].includes(item.status));
  const reviewTasks = submissions.pending;
  const failedImports = store.importJobs.filter((job) => job.status === "failed" || job.invalidRows > 0);
  return <>
    <header className={styles.header}><div><span className={styles.eyebrow}>H2OBOOK OPERATIONS · HÀNG ĐỢI CÔNG VIỆC</span><h1>Việc nào cần xử lý ngay?</h1><p>Tập trung vào bài chờ chấm, học viên cần hỗ trợ, nội dung cần duyệt và dữ liệu cần khắc phục. Mỗi việc đều có trạng thái, người phụ trách và bước tiếp theo.</p></div><div className={styles.headerActions}><button className={`${styles.button} ${styles.buttonSecondary}`} type="button" onClick={() => setShowBriefing((value) => !value)}><BrainCircuit size={16}/>Tóm tắt vận hành</button><Link className={`${styles.button} ${styles.buttonPrimary}`} href="/operations/approvals">Xử lý phê duyệt</Link></div></header>
    {showBriefing && <section className={styles.briefing} aria-live="polite"><BrainCircuit/><div><strong>Tóm tắt cục bộ để người phụ trách rà soát</strong><p>{reviewTasks.length} bài thực hành cần xem, {openTickets.length} yêu cầu hỗ trợ còn mở, {pendingApprovals.length} nội dung đang chờ duyệt và {failedImports.length} lô dữ liệu cần kiểm tra. Đây là gợi ý từ trạng thái hiện có; chưa gửi hay thay đổi dữ liệu nào.</p></div></section>}
    <section className={styles.metrics}><OperationsMetric icon={ClipboardCheck} value={reviewTasks.length} label="Bài chờ chấm"/><OperationsMetric icon={LifeBuoy} value={openTickets.length} label="Học viên cần hỗ trợ"/><OperationsMetric icon={CheckCheck} value={pendingApprovals.length} label="Nội dung chờ duyệt"/><OperationsMetric icon={FileWarning} value={failedImports.length} label="Lô dữ liệu cần kiểm tra"/></section>
    <div className={styles.grid}>
      <section className={`${styles.card} ${styles.span7}`}><div className={styles.cardHead}><div><h2>Hàng đợi ưu tiên</h2><p>Bài nộp thật của học viên, xử lý theo hạn và người phụ trách.</p></div><Link href="/instructor/assessments">Mở hàng đợi <ArrowRight size={13}/></Link></div><div className={styles.cardBody}><div className={styles.workQueue}>{submissions.mode === "loading" && <p className={styles.empty}>Đang tải hàng đợi…</p>}{submissions.error && <p className={styles.empty}>{submissions.error}</p>}{submissions.mode === "production" && reviewTasks.length === 0 && <p className={styles.empty}>Không có bài nào đang chờ chấm.</p>}{reviewTasks.map((task) => <div className={styles.workRow} key={task.id}><span className={styles.listItemIcon}><ClipboardCheck size={16}/></span><div><strong>{task.title}</strong><small>{task.studentName} · {task.dueAt ? `Hạn ${new Intl.DateTimeFormat("vi-VN", { day: "2-digit", month: "2-digit" }).format(new Date(task.dueAt))}` : "Không hạn"}</small></div><StatusBadge value={task.status}/><span className={styles.owner}>Giảng viên</span><Link href="/instructor/assessments">Chấm bài <ArrowRight size={14}/></Link></div>)}{openTickets.slice(0, 2).map((ticket) => <div className={styles.workRow} key={ticket.id}><span className={styles.listItemIcon}><LifeBuoy size={16}/></span><div><strong>{ticket.subject}</strong><small>{ticket.requesterName} · {ticket.code}</small></div><StatusBadge value={ticket.priority}/><span className={styles.owner}>{ticket.assigneeName ?? "Chưa phân công"}</span><Link href="/operations/support">Mở yêu cầu <ArrowRight size={14}/></Link></div>)}</div></div></section>
      <section className={`${styles.card} ${styles.span5}`}><div className={styles.cardHead}><div><h2>Kiểm tra dữ liệu & xuất bản</h2><p>Chỉ áp dụng sau khi người phụ trách xác nhận.</p></div><FileWarning size={18}/></div><div className={styles.cardBody}><div className={styles.list}>{approvals.mode === "demo" && <p className={styles.empty}>Phê duyệt đang ở chế độ demo — chưa nối dữ liệu thật.</p>}{failedImports.map((job) => <div className={styles.listItem} key={job.id}><span className={styles.listItemIcon}><FileWarning size={16}/></span><div><strong>{job.fileName}</strong><small>{job.invalidRows} dòng cần xem · {job.createdBy}</small></div><div className={styles.listItemMeta}><StatusBadge value={job.status}/><Link href="/operations/import-center">Khắc phục</Link></div></div>)}{pendingApprovals.slice(0, 2).map((approval) => <div className={styles.listItem} key={approval.id}><span className={styles.listItemIcon}><CheckCheck size={16}/></span><div><strong>{approval.title}</strong><small>{approval.requesterName} · {approval.reviewerName ?? "Chưa phân công"}</small></div><div className={styles.listItemMeta}><StatusBadge value={approval.status}/><Link href="/operations/approvals">Xem duyệt</Link></div></div>)}</div></div></section>
      <section className={`${styles.card} ${styles.span7}`}><div className={styles.cardHead}><div><h2>Admissions Pulse</h2><p>Khách cần follow-up và hồ sơ chờ hoàn thiện.</p></div><Link href="/operations/admissions">Mở CRM <ArrowRight size={13}/></Link></div><div className={styles.cardBody}><div className={styles.list}>{admissions.mode === "loading" && <p className={styles.empty}>Đang tải…</p>}{admissions.error && <p className={styles.empty}>{admissions.error}</p>}{admissions.mode === "production" && !admissions.error && followUpLeads.length === 0 && <p className={styles.empty}>Chưa có khách cần follow-up.</p>}{followUpLeads.map((lead) => <div className={styles.listItem} key={lead.id}><span className={styles.listItemIcon}><GraduationCap size={16}/></span><div><strong>{lead.name || lead.email}</strong><small>{lead.interest} · {lead.ownerName || lead.source}</small></div><div className={styles.listItemMeta}><StatusBadge value={lead.stage}/><em>{lead.expectedValue > 0 ? `${new Intl.NumberFormat("vi-VN").format(lead.expectedValue)} đ` : "—"}</em></div></div>)}</div></div></section>
      <section className={`${styles.card} ${styles.span5}`}><div className={styles.cardHead}><div><h2>Automation Health</h2><p>Dữ liệu mẫu — chưa nối workflow engine.</p></div><Workflow size={18}/></div><div className={styles.cardBody}><div className={styles.list}>{store.automations.map((automation) => <div className={styles.listItem} key={automation.id}><span className={styles.listItemIcon}><Workflow size={16}/></span><div><strong>{automation.name}</strong><small>{automation.trigger}</small></div><div className={styles.listItemMeta}><StatusBadge value={automation.status}/><em>{automation.runCount} lượt</em></div></div>)}</div></div></section>
      <section className={`${styles.card} ${styles.span6}`}><div className={styles.cardHead}><div><h2>Support Queue</h2><p>{tickets.mode === "demo" ? "Dữ liệu mẫu (demo)." : "Ưu tiên theo mức độ ảnh hưởng."}</p></div><LifeBuoy size={18}/></div><div className={styles.cardBody}><div className={styles.list}>{tickets.mode === "loading" && <p className={styles.empty}>Đang tải…</p>}{tickets.mode === "production" && tickets.rows.length === 0 && <p className={styles.empty}>Chưa có yêu cầu hỗ trợ.</p>}{tickets.rows.slice(0,3).map((ticket) => <div className={styles.listItem} key={ticket.id}><span className={styles.listItemIcon}><LifeBuoy size={16}/></span><div><strong>{ticket.subject}</strong><small>{ticket.requesterName} · {ticket.code}</small></div><div className={styles.listItemMeta}><StatusBadge value={ticket.status}/><em>{ticket.priority}</em></div></div>)}</div></div></section>
      <section className={`${styles.card} ${styles.span6}`}><div className={styles.cardHead}><div><h2>Notification Performance</h2><p>Dữ liệu mẫu — chưa nối nhật ký gửi.</p></div><BellRing size={18}/></div><div className={styles.cardBody}><div className={styles.list}>{store.notificationTemplates.map((item) => <div className={styles.listItem} key={item.id}><span className={styles.listItemIcon}><BellRing size={16}/></span><div><strong>{item.name}</strong><small>{item.channels.join(" · ")}</small></div><div className={styles.listItemMeta}><StatusBadge value={item.enabled ? "active" : "paused"}/><em>{item.sentCount} gửi</em></div></div>)}</div></div></section>
    </div>
  </>;
}
