"use client";

import { useRef, useState } from "react";
import { AppShell } from "@/components/layout/app-shell";
import { Badge } from "@/components/ui/badge";
import { useAppStore } from "@/store/app-store";
import { Check, Cloud, Database, Download, HardDrive, KeyRound, RefreshCw, Save, ShieldCheck, Upload, type LucideIcon } from "lucide-react";
import type { AppDataExport } from "@/types/domain";

export default function SettingsPage() {
  const store = useAppStore();
  const [draft, setDraft] = useState(store.workspace);
  const [saved, setSaved] = useState(false);
  const [message, setMessage] = useState("");
  const backupRef = useRef<HTMLInputElement>(null);
  const save = () => { store.updateWorkspace(draft); setSaved(true); setTimeout(() => setSaved(false), 1500); };
  const exportBackup = () => { const data = store.exportData(); const url = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], { type: "application/json" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `h2obook-backup-${new Date().toISOString().slice(0,10)}.json`; anchor.click(); URL.revokeObjectURL(url); };
  const importBackup = async (file?: File) => { if (!file) return; try { store.importData(JSON.parse(await file.text()) as AppDataExport); setDraft(useAppStore.getState().workspace); setMessage("Khôi phục backup thành công."); } catch (error) { setMessage(error instanceof Error ? error.message : "Không thể khôi phục backup."); } };
  return <AppShell>
    <div className="page-header"><div><span className="eyebrow">WORKSPACE CONFIGURATION</span><h1>Cài đặt hệ thống</h1><p>Cấu hình workspace, hạ tầng, bảo mật và sao lưu dữ liệu.</p></div><button className="btn btn-primary" onClick={save}>{saved ? <Check size={16}/> : <Save size={16}/>} {saved ? "Đã lưu" : "Lưu thay đổi"}</button></div>
    {message && <div className="settings-message"><Check size={15}/>{message}</div>}
    <div className="settings-grid"><section className="section-card"><div className="section-head"><div><h2>Thông tin workspace</h2><p>Hiển thị trong dashboard, hóa đơn và storefront.</p></div></div><div className="section-body form-grid"><label className="field"><span>Tên workspace</span><input className="input" value={draft.name} onChange={(event) => setDraft((value) => ({ ...value, name: event.target.value }))}/></label><label className="field"><span>Slug</span><input className="input" value={draft.slug} onChange={(event) => setDraft((value) => ({ ...value, slug: event.target.value }))}/></label><label className="field"><span>Chủ sở hữu</span><input className="input" value={draft.ownerName} onChange={(event) => setDraft((value) => ({ ...value, ownerName: event.target.value }))}/></label><label className="field"><span>Email quản trị</span><input className="input" value={draft.email} onChange={(event) => setDraft((value) => ({ ...value, email: event.target.value }))}/></label><label className="field"><span>Điện thoại</span><input className="input" value={draft.phone} onChange={(event) => setDraft((value) => ({ ...value, phone: event.target.value }))}/></label><label className="field"><span>Màu hệ thống</span><div className="color-control"><input type="color" value={draft.brandColor} onChange={(event) => setDraft((value) => ({ ...value, brandColor: event.target.value }))}/><input value={draft.brandColor} onChange={(event) => setDraft((value) => ({ ...value, brandColor: event.target.value }))}/></div></label><label className="field full"><span>Tên miền riêng</span><input className="input" value={draft.customDomain ?? ""} onChange={(event) => setDraft((value) => ({ ...value, customDomain: event.target.value }))} placeholder="books.tenhocvien.vn"/></label></div></section>
      <aside className="settings-side-stack"><section className="section-card"><div className="section-head"><div><h2>Dung lượng</h2><p>Cloud storage usage.</p></div><HardDrive size={19}/></div><div className="section-body storage-card"><strong>{(store.workspace.storageUsedMb/1024).toFixed(1)} GB</strong><span>/ {(store.workspace.storageLimitMb/1024).toFixed(0)} GB</span><div className="progress"><span style={{ width: `${store.workspace.storageUsedMb/store.workspace.storageLimitMb*100}%` }}/></div><small>Ảnh, PDF, video, audio và file export.</small></div></section><section className="section-card"><div className="section-head"><div><h2>Sao lưu</h2><p>Local-first data package.</p></div><Database size={19}/></div><div className="section-body backup-actions"><button className="btn btn-secondary" onClick={exportBackup}><Download size={15}/>Tải backup V3</button><button className="btn btn-secondary" onClick={() => backupRef.current?.click()}><Upload size={15}/>Khôi phục backup</button><input ref={backupRef} hidden type="file" accept="application/json,.json" onChange={(event) => importBackup(event.target.files?.[0])}/><button className="btn btn-danger" onClick={() => { if (window.confirm("Khôi phục toàn bộ dữ liệu demo ban đầu?")) { store.resetDemoData(); setDraft(useAppStore.getState().workspace); setMessage("Đã khôi phục dữ liệu demo."); } }}><RefreshCw size={15}/>Reset dữ liệu demo</button></div></section></aside>
      <section className="section-card settings-wide"><div className="section-head"><div><h2>Kết nối production</h2><p>Biến môi trường cần cấu hình khi triển khai thật.</p></div><Badge tone="warning">Demo local-first</Badge></div><div className="section-body integration-grid"><Integration icon={Database} title="Supabase" description="Auth, PostgreSQL, RLS và realtime" keys={["NEXT_PUBLIC_SUPABASE_URL","NEXT_PUBLIC_SUPABASE_ANON_KEY","SUPABASE_SERVICE_ROLE_KEY"]}/><Integration icon={Cloud} title="Cloudflare R2" description="Private asset storage và CDN" keys={["R2_ACCOUNT_ID","R2_ACCESS_KEY_ID","R2_SECRET_ACCESS_KEY","R2_BUCKET"]}/><Integration icon={KeyRound} title="Payment Provider" description="Checkout, QR và webhook" keys={["PAYMENT_PROVIDER","PAYMENT_WEBHOOK_SECRET"]}/><Integration icon={ShieldCheck} title="Security & Monitoring" description="Sentry, rate limit và audit" keys={["SENTRY_DSN","CRON_SECRET","ENCRYPTION_KEY"]}/></div></section>
      <section className="section-card settings-wide"><div className="section-head"><div><h2>Chính sách bảo mật</h2><p>Các nguyên tắc bắt buộc của H2OBOOK.</p></div><ShieldCheck size={19}/></div><div className="section-body security-checklist">{["Bật RLS trên toàn bộ bảng dữ liệu workspace", "Không sử dụng service role key trên trình duyệt", "Tài sản private chỉ mở qua signed URL có thời hạn", "Webhook xác minh chữ ký trước khi cấp entitlement", "Kiểm tra MIME thực tế và giới hạn dung lượng upload", "Ghi audit log cho publish, clone, thanh toán và phân quyền"].map((item) => <div key={item}><Check size={14}/>{item}</div>)}</div></section>
    </div>
  </AppShell>;
}

function Integration({ icon: Icon, title, description, keys }: { icon: LucideIcon; title: string; description: string; keys: string[] }) { return <article className="integration-card"><div className="integration-head"><span><Icon size={19}/></span><div><strong>{title}</strong><small>{description}</small></div></div>{keys.map((key) => <code key={key}>{key}</code>)}</article>; }
