import type { CreativeSurface, CreativeSurfaceDefinition } from "./types";

export const creativeSurfaceRegistry: CreativeSurfaceDefinition[] = [
  {
    id: "assets",
    label: "Kho tài sản production",
    shortLabel: "Tài sản",
    description: "Tải, quét an toàn và quản lý asset ID dùng chung trong toàn workspace.",
    route: "/assets",
    previewRoute: "/creative-publishing-v1-preview/assets",
    stage: 1,
    status: "ready",
    role: "designer",
    dependencies: [],
    outputs: ["asset_id", "signed_url", "scan_status"],
  },
  {
    id: "ingestion",
    label: "Universal Content Ingestion",
    shortLabel: "Nhập nguồn",
    description: "Chuyển DOCX, PDF, hình ảnh, HTML, Markdown, TXT và URL thành BookDocument có cấu trúc.",
    route: "/ingestion",
    previewRoute: "/creative-publishing-v1-preview/ingestion",
    stage: 2,
    status: "ready",
    role: "content_manager",
    dependencies: ["assets"],
    outputs: ["book_document", "preview", "recovery_checkpoint"],
  },
  {
    id: "blocks",
    label: "Block Library",
    shortLabel: "Block",
    description: "Lưu các khối bài học, rubric, profile và CTA để tái sử dụng trong Editor.",
    route: "/blocks",
    previewRoute: "/creative-publishing-v1-preview/blocks",
    stage: 3,
    status: "ready",
    role: "designer",
    dependencies: ["ingestion"],
    outputs: ["reusable_block", "editor_handoff"],
  },
  {
    id: "books",
    label: "Dự án sách",
    shortLabel: "Sách",
    description: "Quản lý vòng đời draft, preview, review, publish và archive của từng sách.",
    route: "/books",
    previewRoute: "/creative-publishing-v1-preview/books",
    stage: 4,
    status: "ready",
    role: "content_manager",
    dependencies: ["ingestion", "blocks"],
    outputs: ["book", "book_version", "review_request"],
  },
  {
    id: "brand-kit",
    label: "Brand Kit",
    shortLabel: "Brand",
    description: "Quản lý logo, màu, font, chuyên gia và Smart Fields theo từng thương hiệu.",
    route: "/brand-kit",
    previewRoute: "/creative-publishing-v1-preview/brand-kit",
    stage: 5,
    status: "ready",
    role: "designer",
    dependencies: ["assets"],
    outputs: ["brand_profile", "smart_fields"],
  },
  {
    id: "templates",
    label: "Kho template sách",
    shortLabel: "Template",
    description: "Đóng gói sách thành template có version, quyền khóa layer và Smart Fields.",
    route: "/templates",
    previewRoute: "/creative-publishing-v1-preview/templates",
    stage: 6,
    status: "ready",
    role: "designer",
    dependencies: ["books", "brand-kit"],
    outputs: ["template_version", "clone_policy"],
  },
  {
    id: "design-library",
    label: "Thư viện thiết kế Makeup",
    shortLabel: "Thiết kế",
    description: "Tạo cover, profile, thiệp, bằng và khuyến mãi rồi mở trực tiếp trong Editor.",
    route: "/design-library",
    previewRoute: "/creative-publishing-v1-preview/design-library",
    stage: 7,
    status: "ready",
    role: "designer",
    dependencies: ["brand-kit", "templates"],
    outputs: ["design_book", "smart_field_values"],
  },
  {
    id: "clones",
    label: "Trung tâm nhân bản sách",
    shortLabel: "Clone",
    description: "Theo dõi linked clone, template version, override và xung đột giữa các thương hiệu.",
    route: "/clones",
    previewRoute: "/creative-publishing-v1-preview/clones",
    stage: 8,
    status: "ready",
    role: "admin",
    dependencies: ["templates", "brand-kit"],
    outputs: ["clone_record", "conflict_resolution"],
  },
  {
    id: "bulk-publishing",
    label: "Bulk Publishing Studio",
    shortLabel: "Bulk",
    description: "Tạo hàng loạt workbook, chứng chỉ và giáo trình từ CSV hoặc Google Sheets.",
    route: "/bulk-publishing",
    previewRoute: "/creative-publishing-v1-preview/bulk-publishing",
    stage: 9,
    status: "ready",
    role: "content_manager",
    dependencies: ["templates", "brand-kit"],
    outputs: ["batch_job", "generated_books"],
  },
  {
    id: "editor",
    label: "H2OBOOK Studio",
    shortLabel: "Editor",
    description: "Compose, layout, text flow, layer, Smart Fields và chỉnh sửa thiết kế chính xác.",
    route: "/editor/book_makeup_pro",
    previewRoute: "/creative-publishing-v1-preview/editor",
    stage: 10,
    status: "ready",
    role: "designer",
    dependencies: ["books", "blocks", "design-library"],
    outputs: ["draft_revision", "layout_document"],
  },
  {
    id: "content-health",
    label: "Kiểm tra chất lượng sách",
    shortLabel: "Preflight",
    description: "Kiểm tra khả năng đọc, accessibility, nhận diện thương hiệu, ảnh và liên kết.",
    route: "/content-health",
    previewRoute: "/creative-publishing-v1-preview/content-health",
    stage: 11,
    status: "ready",
    role: "content_manager",
    dependencies: ["editor"],
    outputs: ["health_report", "blocking_warnings"],
  },
  {
    id: "publish",
    label: "Publish Center",
    shortLabel: "Publish",
    description: "Xuất Web Reader, PDF, EPUB, SCORM và xAPI bằng local hoặc publishing worker.",
    route: "/publish",
    previewRoute: "/creative-publishing-v1-preview/publish",
    stage: 12,
    status: "ready",
    role: "admin",
    dependencies: ["content-health"],
    outputs: ["publication", "artifact", "entitlement"],
  },
];

export const creativeSurfaces = creativeSurfaceRegistry.map((item) => item.id);

export function isCreativeSurface(value: string): value is CreativeSurface {
  return creativeSurfaces.includes(value as CreativeSurface);
}

export function getCreativeSurface(value: CreativeSurface): CreativeSurfaceDefinition {
  const surface = creativeSurfaceRegistry.find((item) => item.id === value);
  if (!surface) throw new Error(`Unknown creative surface: ${value}`);
  return surface;
}
