"use client";
import { Suspense, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import Link from "next/link";
import { AppShell } from "@/components/layout/app-shell";
import { useAppStore } from "@/store/app-store";
import { legacyBookToDocument } from "@h2obook/content-core";
import { buildFixedEpub, buildReflowableEpub, buildScormPackage, buildXapiPackage, exportProfiles, renderFixedLayoutHtml, renderSemanticHtml } from "@h2obook/publishing-core";
import { BookOpen, Download, ExternalLink, FileArchive, FileText, Printer } from "lucide-react";

function download(bytes:Uint8Array|string,name:string,type:string){const blob=typeof bytes==="string"?new Blob([bytes],{type}):new Blob([bytes as BlobPart],{type});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
function slug(value:string){return value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/đ/g,"d").replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"")}
function PublishPageInner(){const params=useSearchParams();const store=useAppStore();const book=store.books.find((item)=>item.id===params.get("book"))??store.books[0];const [profileId,setProfileId]=useState("pdf-web");const [status,setStatus]=useState("Sẵn sàng xuất bản");const profile=exportProfiles.find((item)=>item.id===profileId)??exportProfiles[0];const document=useMemo(()=>book?legacyBookToDocument(book):null,[book]);if(!book||!document)return <AppShell><div className="empty-state">Chưa có sách để xuất bản.</div></AppShell>;
const run=async()=>{setStatus("Đang tạo gói xuất bản...");const name=slug(book.title);if(profile.format==="epub_reflow")download(await buildReflowableEpub(document,profile),`${name}.epub`,"application/epub+zip");else if(profile.format==="epub_fixed")download(await buildFixedEpub(book,profile),`${name}-fixed.epub`,"application/epub+zip");else if(profile.format==="scorm12"||profile.format==="scorm2004")download(await buildScormPackage(document,profile,profile.format==="scorm12"?"1.2":"2004"),`${name}-${profile.format}.zip`,"application/zip");else if(profile.format==="xapi")download(await buildXapiPackage(document,profile),`${name}-xapi.zip`,"application/zip");else{const html=profile.format==="html"?renderSemanticHtml(document,profile):renderFixedLayoutHtml(book,profile);const w=window.open("","_blank");if(w){w.document.open();w.document.write(html);w.document.close();if(profile.format.startsWith("pdf"))setTimeout(()=>w.print(),500)}else download(html,`${name}.html`,"text/html");}setStatus(`Đã tạo ${profile.name}`)};
const queueProduction=async()=>{setStatus("Đang đưa vào hàng đợi production...");const html=profile.format==="epub_reflow"||profile.format==="scorm12"||profile.format==="scorm2004"||profile.format==="xapi"?renderSemanticHtml(document,profile):renderFixedLayoutHtml(book,profile);const response=await fetch("/api/publishing/jobs",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({organizationId:store.workspace.id,bookId:book.id,profileId:profile.id,type:profile.format,html,title:book.title})});const payload=await response.json();setStatus(response.ok?`Đã tạo job ${payload.job?.id??""}`:`Không thể tạo job: ${payload.error??"UNKNOWN"}`)};
return <AppShell><div className="page-header"><div><span className="eyebrow">PROFESSIONAL PUBLISHING</span><h1>Publish Center</h1><p>Một nguồn nội dung, nhiều định dạng web, PDF, EPUB và LMS.</p></div><Link className="btn btn-secondary" href={`/editor/${book.id}`}><BookOpen size={15}/>Quay lại Studio</Link></div><div className="publish-layout"><section className="section-card"><div className="section-head"><div><h2>Chọn hồ sơ xuất bản</h2><p>{book.title}</p></div><FileArchive/></div><div className="publish-profiles">{exportProfiles.map((item)=><button key={item.id} className={profileId===item.id?"active":""} onClick={()=>setProfileId(item.id)}><span>{item.format.startsWith("pdf")?<Printer/>:item.format.includes("epub")?<FileText/>:<FileArchive/>}</span><strong>{item.name}</strong><small>{item.page.width?`${item.page.width}×${item.page.height} ${item.page.unit}`:"Responsive"}</small></button>)}</div><div className="publish-actions"><button className="btn btn-primary" onClick={run}><Download size={16}/>Tạo trên thiết bị</button><button className="btn btn-secondary" onClick={queueProduction}>Đưa vào worker</button><span>{status}</span></div></section><aside className="section-card publish-inspector"><div className="section-head"><h2>Thông số</h2></div><dl><div><dt>Định dạng</dt><dd>{profile.format}</dd></div><div><dt>Bleed</dt><dd>{profile.page.bleed} {profile.page.unit}</dd></div><div><dt>Font nhúng</dt><dd>Có trong worker</dd></div><div><dt>Accessibility</dt><dd>{profile.accessibility.tagged?"Bật":"Tắt"}</dd></div><div><dt>PDF/X</dt><dd>{profile.print?.pdfx??"Không áp dụng"}</dd></div></dl><a className="btn btn-secondary" href="/processing"><ExternalLink size={14}/>Theo dõi export worker</a></aside></div></AppShell>}
export default function PublishPage(){return <Suspense fallback={null}><PublishPageInner/></Suspense>}
