import JSZip from "jszip";
import type { BookDocument } from "@h2obook/content-core";
import type { H2OBook } from "../../../types/editor";
import { renderFixedLayoutHtml, renderSemanticHtml } from "./html";
import type { ExportProfile } from "./types";

const xml=(value:string)=>value.replace(/[&<>"']/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&apos;"})[c]!);
export async function buildReflowableEpub(document:BookDocument,profile:ExportProfile){const zip=new JSZip();zip.file("mimetype","application/epub+zip",{compression:"STORE"});zip.file("META-INF/container.xml",`<?xml version="1.0"?><container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container"><rootfiles><rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/></rootfiles></container>`);const html=renderSemanticHtml(document,profile).replace('<!doctype html>','<?xml version="1.0" encoding="utf-8"?>').replace('<html','<html xmlns="http://www.w3.org/1999/xhtml"');zip.file("OEBPS/book.xhtml",html);zip.file("OEBPS/nav.xhtml",`<?xml version="1.0"?><html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops"><head><title>Mục lục</title></head><body><nav epub:type="toc"><ol><li><a href="book.xhtml">${xml(document.title)}</a></li></ol></nav></body></html>`);zip.file("OEBPS/content.opf",`<?xml version="1.0"?><package xmlns="http://www.idpf.org/2007/opf" version="3.0" unique-identifier="pub-id" xml:lang="${profile.accessibility.language}"><metadata xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:identifier id="pub-id">urn:uuid:${document.id}</dc:identifier><dc:title>${xml(document.title)}</dc:title><dc:language>${profile.accessibility.language}</dc:language><meta property="dcterms:modified">${new Date().toISOString().replace(/\.\d{3}Z$/,"Z")}</meta></metadata><manifest><item id="book" href="book.xhtml" media-type="application/xhtml+xml"/><item id="nav" href="nav.xhtml" media-type="application/xhtml+xml" properties="nav"/></manifest><spine><itemref idref="book"/></spine></package>`);return zip.generateAsync({type:"uint8array",compression:"DEFLATE"});}
export async function buildFixedEpub(book:H2OBook,profile:ExportProfile){const zip=new JSZip();zip.file("mimetype","application/epub+zip",{compression:"STORE"});zip.file("META-INF/container.xml",`<?xml version="1.0"?><container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container"><rootfiles><rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/></rootfiles></container>`);const manifest:string[]=[];const spine:string[]=[];book.pages.forEach((page,index)=>{const one={...book,pages:[page]};const name=`page-${index+1}.xhtml`;zip.file(`OEBPS/${name}`,renderFixedLayoutHtml(one,profile).replace('<!doctype html>','<?xml version="1.0" encoding="utf-8"?>').replace('<html','<html xmlns="http://www.w3.org/1999/xhtml"'));manifest.push(`<item id="p${index+1}" href="${name}" media-type="application/xhtml+xml"/>`);spine.push(`<itemref idref="p${index+1}"/>`)});zip.file("OEBPS/content.opf",`<?xml version="1.0"?><package xmlns="http://www.idpf.org/2007/opf" version="3.0" unique-identifier="pub-id" prefix="rendition: http://www.idpf.org/vocab/rendition/#"><metadata xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:identifier id="pub-id">urn:uuid:${book.id}</dc:identifier><dc:title>${xml(book.title)}</dc:title><dc:language>${profile.accessibility.language}</dc:language><meta property="rendition:layout">pre-paginated</meta><meta property="dcterms:modified">${new Date().toISOString().replace(/\.\d{3}Z$/,"Z")}</meta></metadata><manifest>${manifest.join("")}</manifest><spine>${spine.join("")}</spine></package>`);return zip.generateAsync({type:"uint8array",compression:"DEFLATE"});}
