import type { KnowledgeUniverseNode, KnowledgeUniverseStage } from "./types";

export const knowledgeUniverseNodes: KnowledgeUniverseNode[] = [
  {
    id: "books",
    label: "Thư viện sách",
    shortLabel: "Sách",
    description: "Giáo trình, playbook và sách nghề được tổ chức thành các node tri thức có thể đọc, tìm kiếm và ghi nhớ.",
    href: "/academy/books",
    access: "public",
    orbit: 1,
    angle: 12,
    color: "#ef5b92",
    icon: "books",
    eyebrow: "KNOWLEDGE SOURCE",
    output: "Biến nội dung dài thành hệ thống kiến thức có cấu trúc.",
    metrics: [
      { label: "Nguồn", value: "24" },
      { label: "Chương", value: "126" },
      { label: "Ghi nhớ", value: "82%" },
    ],
  },
  {
    id: "courses",
    label: "Khóa học thực hành",
    shortLabel: "Khóa học",
    description: "Kết nối video, bài học, nhiệm vụ, rubric chấm điểm và Skill Map thành một lộ trình có đầu ra rõ ràng.",
    href: "/academy/courses",
    access: "public",
    orbit: 1,
    angle: 132,
    color: "#49d7e8",
    icon: "courses",
    eyebrow: "LEARNING SYSTEM",
    output: "Chuyển kiến thức thành năng lực có thể đo lường.",
    metrics: [
      { label: "Bài học", value: "84" },
      { label: "Kỹ năng", value: "18" },
      { label: "Tiến độ", value: "68%" },
    ],
  },
  {
    id: "strategy",
    label: "Strategy Hub",
    shortLabel: "Strategy",
    description: "Các chiến lược có khách, định giá, content, tư vấn và vận hành được nối với từng giai đoạn nghề nghiệp.",
    href: "/academy/strategies",
    access: "public",
    orbit: 1,
    angle: 252,
    color: "#d8b36a",
    icon: "strategy",
    eyebrow: "BUSINESS INTELLIGENCE",
    output: "Đưa năng lực chuyên môn vào một hệ thống kinh doanh bền vững.",
    metrics: [
      { label: "Playbook", value: "36" },
      { label: "Checklist", value: "72" },
      { label: "Case", value: "18" },
    ],
  },
  {
    id: "roadmap",
    label: "Lộ trình nghề",
    shortLabel: "Lộ trình",
    description: "Xác định điểm bắt đầu, mốc kỹ năng và bước tiếp theo từ người mới đến Makeup Artist, đội nhóm và học viện.",
    href: "/academy/learning-paths",
    access: "public",
    orbit: 2,
    angle: 35,
    color: "#8f7cf7",
    icon: "roadmap",
    eyebrow: "CAREER NAVIGATION",
    output: "Không học lan man; mỗi giai đoạn đều có một bản đồ.",
    metrics: [
      { label: "Giai đoạn", value: "5" },
      { label: "Mốc nghề", value: "21" },
      { label: "Bước tiếp", value: "01" },
    ],
  },
  {
    id: "student-command",
    label: "Student Command",
    shortLabel: "Học viên",
    description: "Bảng điều khiển cá nhân theo dõi bài đang học, nhiệm vụ hôm nay, kỹ năng yếu và chứng nhận.",
    href: "/student",
    access: "student",
    orbit: 2,
    angle: 125,
    color: "#45c6a8",
    icon: "student",
    eyebrow: "LEARNING TWIN",
    output: "Mỗi học viên có một hồ sơ năng lực số được cập nhật liên tục.",
    metrics: [
      { label: "Học viên", value: "184" },
      { label: "Nhiệm vụ", value: "12" },
      { label: "Skill Map", value: "Live" },
    ],
  },
  {
    id: "mentor",
    label: "H2O Mentor",
    shortLabel: "Mentor",
    description: "Trợ lý điều hướng học tập dựa trên dữ liệu tiến độ; rule-based local hoạt động ngay cả khi AI bên ngoài tắt.",
    href: "/student/mentor",
    access: "student",
    orbit: 2,
    angle: 215,
    color: "#70a5ff",
    icon: "mentor",
    eyebrow: "PERSONAL GUIDANCE",
    output: "Đề xuất bài học, nội dung ôn và nhiệm vụ phù hợp nhất.",
    metrics: [
      { label: "Gợi ý", value: "24/7" },
      { label: "Nguồn", value: "Local" },
      { label: "AI ngoài", value: "Tùy chọn" },
    ],
  },
  {
    id: "design-library",
    label: "Thư viện thiết kế",
    shortLabel: "Thiết kế",
    description: "Template Makeup, bằng tốt nghiệp, thiệp mời, profile và khuyến mãi được cá nhân hóa bằng Brand Kit.",
    href: "/design-library",
    access: "workspace",
    orbit: 2,
    angle: 305,
    color: "#f07ec2",
    icon: "design",
    eyebrow: "CREATIVE INTELLIGENCE",
    output: "Biến dữ liệu thương hiệu thành thiết kế có thể dùng ngay.",
    metrics: [
      { label: "Mẫu", value: "20+" },
      { label: "Smart Fields", value: "On" },
      { label: "Bulk", value: "CSV" },
    ],
  },
  {
    id: "studio",
    label: "H2OBOOK Studio",
    shortLabel: "Studio",
    description: "Không gian biên soạn và thiết kế sách, giáo trình, workbook và nội dung tương tác trên cùng một canvas.",
    href: "/books",
    access: "workspace",
    orbit: 3,
    angle: 25,
    color: "#52d4d0",
    icon: "studio",
    eyebrow: "AUTHORING CORE",
    output: "Tạo một nguồn nội dung và xuất bản ra nhiều trải nghiệm.",
    metrics: [
      { label: "Editor", value: "2.0" },
      { label: "Compose", value: "Semantic" },
      { label: "Flow", value: "Multi-page" },
    ],
  },
  {
    id: "input",
    label: "Input Center",
    shortLabel: "Nạp dữ liệu",
    description: "Nạp DOCX, PDF, ảnh, HTML, Markdown, TXT và URL vào cùng một luồng nhận dạng, preview và chỉnh sửa.",
    href: "/input",
    access: "workspace",
    orbit: 3,
    angle: 145,
    color: "#68a4ff",
    icon: "input",
    eyebrow: "UNIFIED INGESTION",
    output: "Chuyển tài liệu rời rạc thành BookDocument có cấu trúc.",
    metrics: [
      { label: "Định dạng", value: "10" },
      { label: "OCR", value: "Local" },
      { label: "Preview", value: "Unified" },
    ],
  },
  {
    id: "publish",
    label: "Publish Center",
    shortLabel: "Xuất bản",
    description: "Đóng gói tri thức thành Web Reader, PDF, EPUB, SCORM và xAPI từ cùng một nội dung nguồn.",
    href: "/publish",
    access: "workspace",
    orbit: 3,
    angle: 265,
    color: "#ad84ff",
    icon: "publish",
    eyebrow: "MULTI-FORMAT OUTPUT",
    output: "Đưa kiến thức tới người đọc, học viên và hệ thống LMS.",
    metrics: [
      { label: "Đầu ra", value: "7" },
      { label: "Reader", value: "Web" },
      { label: "LMS", value: "SCORM" },
    ],
  },
];

export const knowledgeUniverseStages: KnowledgeUniverseStage[] = [
  {
    id: "ingest",
    index: "01",
    label: "Nạp dữ liệu",
    title: "Thu nhận mọi nguồn tri thức",
    description: "Sách, tài liệu, video, bài học và dữ liệu thực hành được đưa vào một lõi nội dung thống nhất.",
    progress: 38,
    status: "Đang nhận diện nguồn",
  },
  {
    id: "connect",
    index: "02",
    label: "Kết nối",
    title: "Xây mạng quan hệ kiến thức",
    description: "Hệ thống nối kỹ thuật, quy trình, bài tập, chiến lược và mục tiêu nghề thành Knowledge Graph.",
    progress: 64,
    status: "Đang tạo liên kết semantic",
  },
  {
    id: "personalize",
    index: "03",
    label: "Cá nhân hóa",
    title: "Tạo Learning Twin cho học viên",
    description: "Tiến độ, kết quả và mục tiêu được chuyển thành hồ sơ năng lực số của từng người học.",
    progress: 82,
    status: "Đang cập nhật Skill Map",
  },
  {
    id: "act",
    index: "04",
    label: "Hành động",
    title: "Đưa ra bước tiếp theo phù hợp",
    description: "H2O Brain ưu tiên bài học, nội dung ôn, bài thực hành và mốc nghề nghiệp tiếp theo.",
    progress: 100,
    status: "Đã tìm thấy bước tiếp theo",
  },
];
