"use client";

import { useEffect, useMemo, useState } from "react";
import { AppShell } from "@/components/layout/app-shell";
import { Modal } from "@/components/ui/modal";
import { Badge } from "@/components/ui/badge";
import { useAppStore } from "@/store/app-store";
import { formatDate } from "@/lib/utils";
import { MailPlus, MoreHorizontal, Plus, Search, UserCheck, Users } from "lucide-react";
import { publicCourses } from "@/lib/public-site/content";
import type { AcademyApplicationRecord } from "@/lib/academy/demo-store";

export default function StudentsPage() {
  const store = useAppStore();
  const [query, setQuery] = useState("");
  const [open, setOpen] = useState(false);
  const [bulkOpen, setBulkOpen] = useState(false);
  const [bulkText, setBulkText] = useState("");
  const [detailId, setDetailId] = useState<string | null>(null);
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [courseSlug, setCourseSlug] = useState(publicCourses[0]?.slug ?? "");
  const [applications, setApplications] = useState<AcademyApplicationRecord[]>([]);
  const [academyStudents, setAcademyStudents] = useState<typeof store.students>([]);
  const [academyMode, setAcademyMode] = useState<"loading"|"demo"|"production">("loading");
  const [busy, setBusy] = useState("");
  const [feedback, setFeedback] = useState("");
  const studentSource = useMemo(() => academyMode === "production" ? academyStudents : academyStudents.length ? [...academyStudents, ...store.students.filter((student) => !academyStudents.some((item) => item.email === student.email))] : store.students, [academyMode, academyStudents, store.students]);
  const detail = studentSource.find((item) => item.id === detailId);
  const students = useMemo(() => studentSource.filter((item) => `${item.name} ${item.email} ${item.phone}`.toLowerCase().includes(query.toLowerCase())), [studentSource, query]);
  const loadAcademy = async () => {
    const [applicationsResponse, studentsResponse] = await Promise.all([fetch("/api/academy/applications", { cache: "no-store" }), fetch("/api/academy/students", { cache: "no-store" })]);
    if (applicationsResponse.ok) setApplications(((await applicationsResponse.json()).applications ?? []) as AcademyApplicationRecord[]);
    if (studentsResponse.ok) {
      const payload = await studentsResponse.json() as { students?: Array<{id:string;name:string;email:string;phone:string;status:"active"|"invited"|"paused";joinedAt:string;progress:number}>;mode?:"demo"|"production" };
      setAcademyMode(payload.mode ?? "demo");
      setAcademyStudents((payload.students ?? []).map((student) => ({ ...student, classIds: [], completedBooks: 0, lastActiveAt: student.joinedAt })));
    }
  };
  useEffect(() => { void loadAcademy(); }, []);
  const invite = async (person: string, address: string) => {
    const response = await fetch("/api/academy/students/invite", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: person.trim(), email: address.trim(), targetType: courseSlug ? "course" : undefined, targetSlug: courseSlug || undefined }) });
    const payload = await response.json() as { error?: string };
    if (!response.ok) throw new Error(payload.error ?? "STUDENT_INVITE_FAILED");
  };
  const importBulk = async () => { setBusy("bulk"); setFeedback(""); try { const rows=bulkText.split(/\n+/).map((line)=>line.split(",")).filter(([person,address])=>person?.trim()&&address?.trim()); for(const [person,address] of rows) await invite(person,address); setBulkText(""); setBulkOpen(false); setFeedback(`Đã gửi ${rows.length} lời mời tài khoản thật.`); await loadAcademy(); } catch(error){setFeedback(error instanceof Error?error.message:"Không thể gửi lời mời.");} finally{setBusy("");} };
  const create = async () => { setBusy("create"); setFeedback(""); try { await invite(name,email); setOpen(false); setName(""); setEmail(""); setFeedback("Đã tạo tài khoản và gửi email mời học viên."); await loadAcademy(); } catch(error){setFeedback(error instanceof Error?error.message:"Không thể cấp tài khoản.");} finally{setBusy("");} };
  const reviewApplication = async (id:string,action:"approve"|"reject") => { setBusy(id); setFeedback(""); try{const response=await fetch(`/api/academy/applications/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action})});const payload=await response.json() as {error?:string};if(!response.ok)throw new Error(payload.error??"APPLICATION_REVIEW_FAILED");setFeedback(action==="approve"?"Đã duyệt, cấp quyền học và gửi email mời.":"Đã từ chối hồ sơ.");await loadAcademy();}catch(error){setFeedback(error instanceof Error?error.message:"Không thể xử lý hồ sơ.");}finally{setBusy("");} };
  const toggleStudent = async () => { if(!detail)return;if(academyMode!=="production"){store.updateStudent(detail.id,{status:detail.status==="paused"?"active":"paused"});setDetailId(null);return;}setBusy(detail.id);try{const response=await fetch(`/api/academy/students/${detail.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action:detail.status==="active"?"pause":"activate"})});const payload=await response.json() as {error?:string};if(!response.ok)throw new Error(payload.error??"STUDENT_UPDATE_FAILED");setDetailId(null);await loadAcademy();}catch(error){setFeedback(error instanceof Error?error.message:"Không thể cập nhật học viên.");}finally{setBusy("");}};
  return <AppShell>
    <div className="page-header"><div><span className="eyebrow">STUDENT ACCESS</span><h1>Học viên</h1><p>Cấp tài khoản, thư viện, membership và theo dõi tiến độ học.</p></div><div className="header-actions"><button className="btn btn-secondary" onClick={() => setBulkOpen(true)}><MailPlus size={16}/>Mời hàng loạt</button><button className="btn btn-primary" onClick={() => setOpen(true)}><Plus size={16}/>Thêm học viên</button></div></div>
    {feedback&&<div className="academy-admin-feedback">{feedback}</div>}
    <section className="metric-grid compact-metrics"><div className="metric-inline"><Users size={19}/><span><strong>{students.length}</strong>Tổng học viên</span></div><div className="metric-inline"><UserCheck size={19}/><span><strong>{students.filter((item) => item.status === "active").length}</strong>Đang hoạt động</span></div><div className="metric-inline"><MailPlus size={19}/><span><strong>{applications.filter((item) => item.status === "new").length}</strong>Hồ sơ chờ duyệt</span></div><div className="metric-inline"><UserCheck size={19}/><span><strong>{Math.round(students.reduce((sum, item) => sum + item.progress, 0) / Math.max(1, students.length))}%</strong>Tiến độ trung bình</span></div></section>
    <section className="section-card academy-applications-admin"><div className="section-head"><div><h2>Hồ sơ đăng ký từ Academy</h2><p>Lead công khai chảy trực tiếp vào đây. Duyệt sẽ tạo Supabase Auth user, cấp entitlement và gửi email.</p></div><Badge tone={applications.some(item=>item.status==="new")?"warning":"success"}>{applications.filter(item=>item.status==="new").length} chờ duyệt</Badge></div><div className="table-responsive"><table className="data-table"><thead><tr><th>Người đăng ký</th><th>Sản phẩm</th><th>Nguồn</th><th>Ngày gửi</th><th>Trạng thái</th><th/></tr></thead><tbody>{applications.length?applications.map(application=><tr key={application.id}><td><div className="table-user"><span className="mini-avatar">{application.name.split(" ").slice(-2).map(part=>part[0]).join("")}</span><span><strong>{application.name}</strong><small>{application.email}<br/>{application.phone}</small></span></div></td><td><strong>{application.targetName}</strong><br/><small>{application.targetType}</small></td><td>{application.source}</td><td>{formatDate(application.createdAt)}</td><td><Badge tone={application.status==="new"?"warning":application.status==="rejected"?"neutral":"success"}>{application.status}</Badge></td><td>{application.status==="new"&&<div className="academy-review-actions"><button disabled={busy===application.id} onClick={()=>void reviewApplication(application.id,"approve")}>Duyệt & cấp tài khoản</button><button disabled={busy===application.id} onClick={()=>void reviewApplication(application.id,"reject")}>Từ chối</button></div>}</td></tr>):<tr><td colSpan={6}><div className="table-empty">Chưa có hồ sơ đăng ký công khai.</div></td></tr>}</tbody></table></div></section>
    <section className="section-card"><div className="table-toolbar"><div className="search-box compact"><Search size={16}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Tìm học viên theo tên, email, điện thoại..."/></div><span className="result-count">{students.length} học viên</span></div><div className="table-responsive"><table className="data-table"><thead><tr><th>Học viên</th><th>Lớp học</th><th>Tiến độ</th><th>Sách hoàn thành</th><th>Hoạt động cuối</th><th>Trạng thái</th><th/></tr></thead><tbody>{students.map((student) => <tr key={student.id}><td><div className="table-user"><span className="mini-avatar">{student.name.split(" ").slice(-2).map((part) => part[0]).join("")}</span><span><strong>{student.name}</strong><small>{student.email}<br/>{student.phone}</small></span></div></td><td>{student.classIds.length ? student.classIds.map((id) => store.classes.find((item) => item.id === id)?.code).filter(Boolean).join(", ") : "Chưa xếp lớp"}</td><td><div className="progress-cell"><div className="progress"><span style={{ width: `${student.progress}%` }}/></div><strong>{student.progress}%</strong></div></td><td>{student.completedBooks}</td><td>{formatDate(student.lastActiveAt)}</td><td><Badge tone={student.status === "active" ? "success" : student.status === "invited" ? "warning" : "neutral"}>{student.status === "active" ? "Đang học" : student.status === "invited" ? "Đã mời" : "Tạm dừng"}</Badge></td><td><button className="icon-btn" title="Xem học viên" onClick={() => setDetailId(student.id)}><MoreHorizontal size={15}/></button></td></tr>)}</tbody></table></div></section>

    <Modal open={bulkOpen} onClose={() => setBulkOpen(false)} title="Mời học viên hàng loạt" description="Mỗi dòng theo định dạng: Họ tên,email@example.com. Hệ thống sẽ tạo Auth user và gửi email thật khi chạy Production."><label className="field"><span>Danh sách học viên</span><textarea className="textarea bulk-textarea" value={bulkText} onChange={(event) => setBulkText(event.target.value)} placeholder={"Nguyễn Minh Anh,minhanh@example.com\nTrần Thu Hà,thuha@example.com"}/></label><div className="modal-actions"><button className="btn btn-secondary" onClick={() => setBulkOpen(false)}>Hủy</button><button className="btn btn-primary" disabled={busy==="bulk"} onClick={()=>void importBulk()}><MailPlus size={15}/>{busy==="bulk"?"Đang gửi...":"Tạo lời mời"}</button></div></Modal>
    <Modal open={Boolean(detail)} onClose={() => setDetailId(null)} title={detail?.name ?? "Thông tin học viên"} description={detail?.email} width={660}><div className="student-detail-grid"><div><span>Điện thoại</span><strong>{detail?.phone || "Chưa cập nhật"}</strong></div><div><span>Tiến độ</span><strong>{detail?.progress ?? 0}%</strong></div><div><span>Sách hoàn thành</span><strong>{detail?.completedBooks ?? 0}</strong></div><div><span>Hoạt động cuối</span><strong>{detail ? formatDate(detail.lastActiveAt) : ""}</strong></div></div><div className="progress"><span style={{ width: `${detail?.progress ?? 0}%` }}/></div><div className="modal-actions"><button className="btn btn-secondary" onClick={() => setDetailId(null)}>Đóng</button><button className="btn btn-primary" disabled={busy===detail?.id} onClick={()=>void toggleStudent()}>{detail?.status === "paused" ? "Kích hoạt lại" : "Tạm dừng tài khoản"}</button></div></Modal>
    <Modal open={open} onClose={() => setOpen(false)} title="Thêm học viên" description="Tạo Supabase Auth user, gửi email mời và cấp quyền khóa học được chọn."><div className="form-grid"><label className="field"><span>Họ tên</span><input className="input" value={name} onChange={(event) => setName(event.target.value)} placeholder="Nguyễn Minh Anh"/></label><label className="field"><span>Email</span><input className="input" type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="email@example.com"/></label><label className="field full"><span>Cấp quyền khóa học</span><select className="select" value={courseSlug} onChange={(event) => setCourseSlug(event.target.value)}><option value="">Chỉ tạo tài khoản</option>{publicCourses.map((course) => <option key={course.slug} value={course.slug}>{course.title}</option>)}</select></label></div><div className="modal-actions"><button className="btn btn-secondary" onClick={() => setOpen(false)}>Hủy</button><button className="btn btn-primary" disabled={busy==="create"} onClick={()=>void create()}><Plus size={15}/>{busy==="create"?"Đang cấp...":"Thêm và cấp tài khoản"}</button></div></Modal>
  </AppShell>;
}
