"use client";

import { useMemo, useState } from "react";
import { AppShell } from "@/components/layout/app-shell";
import { Modal } from "@/components/ui/modal";
import { Badge } from "@/components/ui/badge";
import { useAppStore } from "@/store/app-store";
import { formatDate } from "@/lib/utils";
import { MailPlus, MoreHorizontal, Plus, Search, UserCheck, Users } from "lucide-react";

export default function StudentsPage() {
  const store = useAppStore();
  const [query, setQuery] = useState("");
  const [open, setOpen] = useState(false);
  const [bulkOpen, setBulkOpen] = useState(false);
  const [bulkText, setBulkText] = useState("");
  const [detailId, setDetailId] = useState<string | null>(null);
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [classId, setClassId] = useState(store.classes.find((item) => item.status === "active")?.id ?? "");
  const detail = store.students.find((item) => item.id === detailId);
  const students = useMemo(() => store.students.filter((item) => `${item.name} ${item.email} ${item.phone}`.toLowerCase().includes(query.toLowerCase())), [store.students, query]);
  const importBulk = () => { bulkText.split(/\n+/).map((line) => line.split(",")).filter(([person,email]) => person?.trim() && email?.trim()).forEach(([person,email]) => store.createStudent({ name: person.trim(), email: email.trim(), status: "invited" })); setBulkText(""); setBulkOpen(false); };
  const create = () => { const student = store.createStudent({ name: name.trim() || "Học viên mới", email: email.trim() || `student${Date.now()}@example.com`, status: classId ? "active" : "invited" }); if (classId) store.enrollStudent(classId, student.id); setOpen(false); setName(""); setEmail(""); };
  return <AppShell>
    <div className="page-header"><div><span className="eyebrow">STUDENT ACCESS</span><h1>Học viên</h1><p>Cấp tài khoản, thư viện, membership và theo dõi tiến độ học.</p></div><div className="header-actions"><button className="btn btn-secondary" onClick={() => setBulkOpen(true)}><MailPlus size={16}/>Mời hàng loạt</button><button className="btn btn-primary" onClick={() => setOpen(true)}><Plus size={16}/>Thêm học viên</button></div></div>
    <section className="metric-grid compact-metrics"><div className="metric-inline"><Users size={19}/><span><strong>{store.students.length}</strong>Tổng học viên</span></div><div className="metric-inline"><UserCheck size={19}/><span><strong>{store.students.filter((item) => item.status === "active").length}</strong>Đang hoạt động</span></div><div className="metric-inline"><MailPlus size={19}/><span><strong>{store.students.filter((item) => item.status === "invited").length}</strong>Chờ kích hoạt</span></div><div className="metric-inline"><UserCheck size={19}/><span><strong>{Math.round(store.students.reduce((sum, item) => sum + item.progress, 0) / Math.max(1, store.students.length))}%</strong>Tiến độ trung bình</span></div></section>
    <section className="section-card"><div className="table-toolbar"><div className="search-box compact"><Search size={16}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Tìm học viên theo tên, email, điện thoại..."/></div><span className="result-count">{students.length} học viên</span></div><div className="table-responsive"><table className="data-table"><thead><tr><th>Học viên</th><th>Lớp học</th><th>Tiến độ</th><th>Sách hoàn thành</th><th>Hoạt động cuối</th><th>Trạng thái</th><th/></tr></thead><tbody>{students.map((student) => <tr key={student.id}><td><div className="table-user"><span className="mini-avatar">{student.name.split(" ").slice(-2).map((part) => part[0]).join("")}</span><span><strong>{student.name}</strong><small>{student.email}<br/>{student.phone}</small></span></div></td><td>{student.classIds.length ? student.classIds.map((id) => store.classes.find((item) => item.id === id)?.code).filter(Boolean).join(", ") : "Chưa xếp lớp"}</td><td><div className="progress-cell"><div className="progress"><span style={{ width: `${student.progress}%` }}/></div><strong>{student.progress}%</strong></div></td><td>{student.completedBooks}</td><td>{formatDate(student.lastActiveAt)}</td><td><Badge tone={student.status === "active" ? "success" : student.status === "invited" ? "warning" : "neutral"}>{student.status === "active" ? "Đang học" : student.status === "invited" ? "Đã mời" : "Tạm dừng"}</Badge></td><td><button className="icon-btn" title="Xem học viên" onClick={() => setDetailId(student.id)}><MoreHorizontal size={15}/></button></td></tr>)}</tbody></table></div></section>

    <Modal open={bulkOpen} onClose={() => setBulkOpen(false)} title="Mời học viên hàng loạt" description="Mỗi dòng theo định dạng: Họ tên,email@example.com"><label className="field"><span>Danh sách học viên</span><textarea className="textarea bulk-textarea" value={bulkText} onChange={(event) => setBulkText(event.target.value)} placeholder={"Nguyễn Minh Anh,minhanh@example.com\nTrần Thu Hà,thuha@example.com"}/></label><div className="modal-actions"><button className="btn btn-secondary" onClick={() => setBulkOpen(false)}>Hủy</button><button className="btn btn-primary" onClick={importBulk}><MailPlus size={15}/>Tạo lời mời</button></div></Modal>
    <Modal open={Boolean(detail)} onClose={() => setDetailId(null)} title={detail?.name ?? "Thông tin học viên"} description={detail?.email} width={660}><div className="student-detail-grid"><div><span>Điện thoại</span><strong>{detail?.phone || "Chưa cập nhật"}</strong></div><div><span>Tiến độ</span><strong>{detail?.progress ?? 0}%</strong></div><div><span>Sách hoàn thành</span><strong>{detail?.completedBooks ?? 0}</strong></div><div><span>Hoạt động cuối</span><strong>{detail ? formatDate(detail.lastActiveAt) : ""}</strong></div></div><div className="progress"><span style={{ width: `${detail?.progress ?? 0}%` }}/></div><div className="modal-actions"><button className="btn btn-secondary" onClick={() => setDetailId(null)}>Đóng</button><button className="btn btn-primary" onClick={() => detail && store.updateStudent(detail.id, { status: detail.status === "paused" ? "active" : "paused" })}>{detail?.status === "paused" ? "Kích hoạt lại" : "Tạm dừng tài khoản"}</button></div></Modal>
    <Modal open={open} onClose={() => setOpen(false)} title="Thêm học viên" description="Học viên sẽ nhận quyền truy cập theo lớp được chọn."><div className="form-grid"><label className="field"><span>Họ tên</span><input className="input" value={name} onChange={(event) => setName(event.target.value)} placeholder="Nguyễn Minh Anh"/></label><label className="field"><span>Email</span><input className="input" type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="email@example.com"/></label><label className="field full"><span>Xếp vào lớp</span><select className="select" value={classId} onChange={(event) => setClassId(event.target.value)}><option value="">Chưa xếp lớp</option>{store.classes.map((course) => <option key={course.id} value={course.id}>{course.name}</option>)}</select></label></div><div className="modal-actions"><button className="btn btn-secondary" onClick={() => setOpen(false)}>Hủy</button><button className="btn btn-primary" onClick={create}><Plus size={15}/>Thêm và cấp tài khoản</button></div></Modal>
  </AppShell>;
}
