-- H2OBOOK 4.4 Professional Publishing Engine
create table if not exists public.publishing_profiles(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,book_id uuid references public.books(id) on delete cascade,name text not null,profile_type text not null,settings jsonb not null default '{}'::jsonb,is_default boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table if not exists public.publishing_jobs(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,book_id uuid not null references public.books(id) on delete cascade,book_version_id uuid references public.book_versions(id) on delete set null,profile_id text not null,format text not null check(format in ('pdf_web','pdf_print','epub_reflow','epub_fixed','scorm12','scorm2004','xapi')),status text not null default 'queued' check(status in ('queued','processing','completed','failed','cancelled')),progress integer not null default 0,queue_job_id text,input jsonb not null default '{}'::jsonb,output jsonb not null default '{}'::jsonb,error_message text,created_by uuid references public.profiles(id) on delete set null,started_at timestamptz,completed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table if not exists public.publishing_artifacts(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,publishing_job_id uuid not null references public.publishing_jobs(id) on delete cascade,book_id uuid not null references public.books(id) on delete cascade,format text not null,storage_key text not null,mime_type text not null,size_bytes bigint not null default 0,checksum text,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now()
);
create table if not exists public.lms_packages(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,book_id uuid not null references public.books(id) on delete cascade,artifact_id uuid references public.publishing_artifacts(id) on delete set null,standard text not null check(standard in ('scorm12','scorm2004','xapi','lti13')),completion_rule jsonb not null default '{}'::jsonb,grade_rule jsonb not null default '{}'::jsonb,created_at timestamptz not null default now()
);
create index if not exists publishing_jobs_org_status_idx on public.publishing_jobs(organization_id,status,created_at desc);create index if not exists publishing_artifacts_book_idx on public.publishing_artifacts(book_id,created_at desc);
alter table public.publishing_profiles enable row level security;alter table public.publishing_jobs enable row level security;alter table public.publishing_artifacts enable row level security;alter table public.lms_packages enable row level security;
do $$ declare t text;begin foreach t in array array['publishing_profiles','publishing_jobs','publishing_artifacts','lms_packages'] loop execute format('create policy %I_read on public.%I for select using(public.is_org_member(organization_id))',t,t);execute format('create policy %I_write on public.%I for all using(public.has_org_role(organization_id,array[''owner'',''admin'',''designer'']::public.member_role[])) with check(public.has_org_role(organization_id,array[''owner'',''admin'',''designer'']::public.member_role[]))',t,t);end loop;end $$;
