-- H2OBOOK 4.5 Universal Content Ingestion
create table if not exists public.ingestion_sources(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,source_type text not null,source_url text,title text not null,asset_id uuid references public.assets(id) on delete set null,content_hash text,metadata jsonb not null default '{}'::jsonb,status text not null default 'ready' check(status in ('pending','ready','blocked','failed')),created_by uuid references public.profiles(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table if not exists public.ingestion_runs(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,source_id uuid references public.ingestion_sources(id) on delete set null,source_type text not null,source_url text,title text not null,status text not null default 'queued' check(status in ('queued','extracting','normalizing','previewed','approved','completed','failed','cancelled')),progress integer not null default 0,preview jsonb not null default '{}'::jsonb,settings jsonb not null default '{}'::jsonb,error_message text,book_id uuid references public.books(id) on delete set null,created_by uuid references public.profiles(id) on delete set null,started_at timestamptz,completed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table if not exists public.ingestion_segments(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,run_id uuid not null references public.ingestion_runs(id) on delete cascade,segment_type text not null,position integer not null,source_text text,normalized_node jsonb not null default '{}'::jsonb,confidence numeric(5,4),manual_status text not null default 'unreviewed' check(manual_status in ('unreviewed','accepted','edited','rejected')),created_at timestamptz not null default now()
);
create table if not exists public.ingestion_mappings(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,run_id uuid not null references public.ingestion_runs(id) on delete cascade,source_path text not null,target_node_type text not null,rules jsonb not null default '{}'::jsonb,created_at timestamptz not null default now()
);
create index if not exists ingestion_runs_org_status_idx on public.ingestion_runs(organization_id,status,created_at desc);create index if not exists ingestion_segments_run_position_idx on public.ingestion_segments(run_id,position);
alter table public.ingestion_sources enable row level security;alter table public.ingestion_runs enable row level security;alter table public.ingestion_segments enable row level security;alter table public.ingestion_mappings enable row level security;
do $$ declare t text;begin foreach t in array array['ingestion_sources','ingestion_runs','ingestion_segments','ingestion_mappings'] loop execute format('drop policy if exists %I_read on public.%I',t,t);execute format('create policy %I_read on public.%I for select using(public.is_org_member(organization_id))',t,t);execute format('drop policy if exists %I_write on public.%I',t,t);execute format('create policy %I_write on public.%I for all using(public.has_org_role(organization_id,array[''owner'',''admin'',''designer'']::public.member_role[])) with check(public.has_org_role(organization_id,array[''owner'',''admin'',''designer'']::public.member_role[]))',t,t);end loop;end $$;
