-- H2OBOOK 4.7 Growth Reader and Content Commerce
create table if not exists public.reader_campaigns(id uuid primary key default gen_random_uuid(),client_key text unique,organization_id uuid not null references public.organizations(id) on delete cascade,book_id uuid not null references public.books(id) on delete cascade,name text not null,status text not null default 'draft' check(status in ('draft','active','paused','archived')),preview_pages integer not null default 5,lead_gate_page integer,lead_fields jsonb not null default '["name","email"]'::jsonb,download_requires_lead boolean not null default false,cta_page integer,cta_label text,cta_url text,utm_capture boolean not null default true,crm_webhook_enabled boolean not null default false,settings jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.reader_leads(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,book_id uuid not null references public.books(id) on delete cascade,campaign_id uuid references public.reader_campaigns(id) on delete set null,email text not null,name text,phone text,company text,utm jsonb not null default '{}'::jsonb,session_id text,consent jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),unique(campaign_id,email));
create table if not exists public.protected_embeds(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,book_id uuid not null references public.books(id) on delete cascade,enabled boolean not null default true,allowed_domains text[] not null default '{}',token_ttl_seconds integer not null default 600,settings jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(book_id));
create table if not exists public.reader_ctas(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,campaign_id uuid not null references public.reader_campaigns(id) on delete cascade,page_number integer not null,label text not null,target_url text not null,cta_type text not null default 'button',settings jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists public.reader_sessions(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,book_id uuid not null references public.books(id) on delete cascade,campaign_id uuid references public.reader_campaigns(id) on delete set null,user_id uuid references public.profiles(id) on delete set null,anonymous_id text,utm jsonb not null default '{}'::jsonb,referrer text,started_at timestamptz not null default now(),ended_at timestamptz,last_page integer not null default 1,max_page integer not null default 1,lead_id uuid references public.reader_leads(id) on delete set null,created_at timestamptz not null default now());
create index if not exists reader_campaigns_book_status_idx on public.reader_campaigns(book_id,status);create index if not exists reader_leads_org_created_idx on public.reader_leads(organization_id,created_at desc);create index if not exists reader_sessions_book_started_idx on public.reader_sessions(book_id,started_at desc);
alter table public.reader_campaigns enable row level security;alter table public.reader_leads enable row level security;alter table public.protected_embeds enable row level security;alter table public.reader_ctas enable row level security;alter table public.reader_sessions enable row level security;
do $$ declare t text;begin foreach t in array array['reader_campaigns','reader_leads','protected_embeds','reader_ctas','reader_sessions'] loop execute format('create policy %I_read on public.%I for select using(public.is_org_member(organization_id))',t,t);execute format('create policy %I_write on public.%I for all using(public.has_org_role(organization_id,array[''owner'',''admin'',''designer'']::public.member_role[])) with check(public.has_org_role(organization_id,array[''owner'',''admin'',''designer'']::public.member_role[]))',t,t);end loop;end $$;
