-- H2OBOOK 4.8 Education Collaboration and Accessibility
create table if not exists public.student_remixes(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,master_book_id uuid not null references public.books(id) on delete cascade,master_version_id uuid references public.book_versions(id) on delete set null,student_id uuid not null references public.profiles(id) on delete cascade,class_id uuid references public.classes(id) on delete set null,status text not null default 'draft' check(status in ('draft','submitted','reviewed','returned')),progress integer not null default 0,submitted_at timestamptz,reviewed_at timestamptz,reviewed_by uuid references public.profiles(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(master_book_id,student_id,class_id));
create table if not exists public.remix_responses(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,remix_id uuid not null references public.student_remixes(id) on delete cascade,page_id text not null,block_id text,response_type text not null check(response_type in ('text','image','file','checklist')),text_response text,asset_id uuid references public.assets(id) on delete set null,status text not null default 'draft' check(status in ('draft','submitted','reviewed')),teacher_feedback text,score numeric(6,2),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.class_progress_cells(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,class_id uuid not null references public.classes(id) on delete cascade,student_id uuid not null references public.profiles(id) on delete cascade,assignment_id uuid references public.assignments(id) on delete cascade,book_id uuid references public.books(id) on delete cascade,page_id text,status text not null default 'not_started' check(status in ('not_started','in_progress','submitted','reviewed','late')),progress integer not null default 0,score numeric(6,2),last_activity_at timestamptz,updated_at timestamptz not null default now(),unique(class_id,student_id,assignment_id,page_id));
create table if not exists public.accessibility_profiles(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,font_scale numeric(4,2) not null default 1,high_contrast boolean not null default false,dyslexia_friendly boolean not null default false,reduced_motion boolean not null default false,text_to_speech_rate numeric(4,2) not null default 1,settings jsonb not null default '{}'::jsonb,updated_at timestamptz not null default now(),unique(user_id));
create table if not exists public.accessibility_reports(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,book_id uuid not null references public.books(id) on delete cascade,book_version_id uuid references public.book_versions(id) on delete set null,score integer not null default 0,issues jsonb not null default '[]'::jsonb,reading_order jsonb not null default '[]'::jsonb,created_by uuid references public.profiles(id) on delete set null,created_at timestamptz not null default now());
create index if not exists remixes_student_status_idx on public.student_remixes(student_id,status,updated_at desc);create index if not exists class_progress_matrix_idx on public.class_progress_cells(class_id,student_id,assignment_id);
alter table public.student_remixes enable row level security;alter table public.remix_responses enable row level security;alter table public.class_progress_cells enable row level security;alter table public.accessibility_profiles enable row level security;alter table public.accessibility_reports enable row level security;
create policy remixes_student_read on public.student_remixes for select using(student_id=auth.uid() or public.has_org_role(organization_id,array['owner','admin','teacher']::public.member_role[]));create policy remixes_student_write on public.student_remixes for all using(student_id=auth.uid() or public.has_org_role(organization_id,array['owner','admin','teacher']::public.member_role[])) with check(student_id=auth.uid() or public.has_org_role(organization_id,array['owner','admin','teacher']::public.member_role[]));
create policy responses_read on public.remix_responses for select using(exists(select 1 from public.student_remixes r where r.id=remix_id and (r.student_id=auth.uid() or public.has_org_role(r.organization_id,array['owner','admin','teacher']::public.member_role[]))));create policy responses_write on public.remix_responses for all using(exists(select 1 from public.student_remixes r where r.id=remix_id and (r.student_id=auth.uid() or public.has_org_role(r.organization_id,array['owner','admin','teacher']::public.member_role[])))) with check(public.is_org_member(organization_id));
create policy class_progress_read on public.class_progress_cells for select using(student_id=auth.uid() or public.has_org_role(organization_id,array['owner','admin','teacher']::public.member_role[]));create policy class_progress_write on public.class_progress_cells for all using(public.has_org_role(organization_id,array['owner','admin','teacher']::public.member_role[])) with check(public.has_org_role(organization_id,array['owner','admin','teacher']::public.member_role[]));
create policy accessibility_profile_self on public.accessibility_profiles for all using(user_id=auth.uid()) with check(user_id=auth.uid());create policy accessibility_reports_read on public.accessibility_reports for select using(public.is_org_member(organization_id));create policy accessibility_reports_write on public.accessibility_reports for all using(public.has_org_role(organization_id,array['owner','admin','designer','teacher']::public.member_role[])) with check(public.has_org_role(organization_id,array['owner','admin','designer','teacher']::public.member_role[]));
