-- H2OBOOK 4.9 Analytics Event Engine
alter table public.analytics_events add column if not exists event_id uuid;alter table public.analytics_events add column if not exists resource_client_key text;alter table public.analytics_events add column if not exists received_at timestamptz not null default now();alter table public.analytics_events add column if not exists schema_version integer not null default 1;
create unique index if not exists analytics_event_id_unique on public.analytics_events(event_id) where event_id is not null;create index if not exists analytics_session_idx on public.analytics_events(session_id,occurred_at);create index if not exists analytics_resource_client_idx on public.analytics_events(resource_client_key,event_name,occurred_at desc);
create table if not exists public.analytics_consents(id uuid primary key default gen_random_uuid(),organization_id uuid references public.organizations(id) on delete cascade,user_id uuid references public.profiles(id) on delete cascade,anonymous_id text,analytics_allowed boolean not null default true,marketing_allowed boolean not null default false,source text not null default 'reader',updated_at timestamptz not null default now(),check(user_id is not null or anonymous_id is not null));
create table if not exists public.analytics_daily_rollups(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,event_date date not null,book_id uuid references public.books(id) on delete cascade,metrics jsonb not null default '{}'::jsonb,updated_at timestamptz not null default now(),unique(organization_id,event_date,book_id));
create table if not exists public.analytics_funnel_definitions(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,name text not null,steps jsonb not null default '[]'::jsonb,window_days integer not null default 30,active boolean not null default true,created_at timestamptz not null default now());
alter table public.analytics_consents enable row level security;alter table public.analytics_daily_rollups enable row level security;alter table public.analytics_funnel_definitions enable row level security;
create policy analytics_consent_self on public.analytics_consents for all using(user_id=auth.uid() or (organization_id is not null and public.has_org_role(organization_id,array['owner','admin']::public.member_role[]))) with check(user_id=auth.uid() or (organization_id is not null and public.has_org_role(organization_id,array['owner','admin']::public.member_role[])));
create policy analytics_rollups_read on public.analytics_daily_rollups for select using(public.has_org_role(organization_id,array['owner','admin','teacher']::public.member_role[]));create policy analytics_rollups_write on public.analytics_daily_rollups for all using(public.has_org_role(organization_id,array['owner','admin']::public.member_role[])) with check(public.has_org_role(organization_id,array['owner','admin']::public.member_role[]));
create policy funnel_read on public.analytics_funnel_definitions for select using(public.has_org_role(organization_id,array['owner','admin','teacher']::public.member_role[]));create policy funnel_write on public.analytics_funnel_definitions for all using(public.has_org_role(organization_id,array['owner','admin']::public.member_role[])) with check(public.has_org_role(organization_id,array['owner','admin']::public.member_role[]));
