-- H2OBOOK 4.10 Optional AI Assistance: disabled by default
create table if not exists public.optional_ai_policies(id uuid primary key default gen_random_uuid(),organization_id uuid not null unique references public.organizations(id) on delete cascade,enabled boolean not null default false,default_mode text not null default 'local' check(default_mode in ('local','external')),monthly_budget_usd numeric(12,4) not null default 0,spent_usd numeric(12,6) not null default 0,billing_period date not null default date_trunc('month',now())::date,max_prompt_characters integer not null default 60000,cache_enabled boolean not null default true,allowed_tasks text[] not null default array['outline','rewrite','quiz','summary','brand_copy','translate','accessibility'],allow_image_input boolean not null default false,allow_external_sources boolean not null default false,settings jsonb not null default '{}'::jsonb,updated_by uuid references public.profiles(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.optional_ai_usage(id bigint generated always as identity primary key,organization_id uuid not null references public.organizations(id) on delete cascade,user_id uuid references public.profiles(id) on delete set null,task_type text not null,provider text not null,model text,input_tokens integer not null default 0,output_tokens integer not null default 0,cost_usd numeric(12,6) not null default 0,cache_hit boolean not null default false,request_hash text,created_at timestamptz not null default now());
create table if not exists public.optional_ai_cache(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,cache_key text not null,task_type text not null,provider text not null,output text not null,usage jsonb not null default '{}'::jsonb,expires_at timestamptz not null,created_at timestamptz not null default now(),unique(organization_id,cache_key));
create index if not exists optional_ai_usage_org_month_idx on public.optional_ai_usage(organization_id,created_at desc);create index if not exists optional_ai_cache_expiry_idx on public.optional_ai_cache(expires_at);
alter table public.optional_ai_policies enable row level security;alter table public.optional_ai_usage enable row level security;alter table public.optional_ai_cache enable row level security;
create policy optional_ai_policy_read on public.optional_ai_policies for select using(public.is_org_member(organization_id));create policy optional_ai_policy_write on public.optional_ai_policies for all using(public.has_org_role(organization_id,array['owner','admin']::public.member_role[])) with check(public.has_org_role(organization_id,array['owner','admin']::public.member_role[]));
create policy optional_ai_usage_read on public.optional_ai_usage for select using(public.has_org_role(organization_id,array['owner','admin']::public.member_role[]));create policy optional_ai_usage_insert on public.optional_ai_usage for insert with check(public.is_org_member(organization_id));
create policy optional_ai_cache_read on public.optional_ai_cache for select using(public.is_org_member(organization_id));create policy optional_ai_cache_write on public.optional_ai_cache for all using(public.has_org_role(organization_id,array['owner','admin','designer','teacher']::public.member_role[])) with check(public.has_org_role(organization_id,array['owner','admin','designer','teacher']::public.member_role[]));
create or replace function public.increment_optional_ai_spend(p_organization_id uuid,p_amount numeric) returns void language plpgsql security definer set search_path=public as $$begin if not public.is_org_member(p_organization_id) then raise exception 'workspace forbidden';end if;update public.optional_ai_policies set spent_usd=case when billing_period=date_trunc('month',now())::date then spent_usd+greatest(p_amount,0) else greatest(p_amount,0) end,billing_period=date_trunc('month',now())::date,updated_at=now() where organization_id=p_organization_id;end$$;revoke all on function public.increment_optional_ai_spend(uuid,numeric) from public;grant execute on function public.increment_optional_ai_spend(uuid,numeric) to authenticated;
