-- H2OBOOK 4.11 Marketplace and Enterprise Scale
-- platform_admin is not yet a real role in public.member_role (see 0001_h2obook_core.sql) or in
-- any accounts table, so this returns false until a follow-up migration introduces a real
-- platform-admin account model. Until then, marketplace moderation and SLA-incident writes are
-- deny-by-default for every authenticated user, which matches NEXT_PUBLIC_PLATFORM_ADMIN_V1=false.
create or replace function public.is_platform_admin()
returns boolean language sql stable as $$
  select false;
$$;

create table if not exists public.marketplace_listings(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,owner_id uuid references public.profiles(id) on delete set null,slug text not null unique,title text not null,description text not null default '',cover_asset_id uuid references public.assets(id) on delete set null,listing_type text not null check(listing_type in ('book','template','bundle','membership','license')),resource_id uuid,resource_client_key text,price numeric(14,2) not null default 0,currency text not null default 'VND',status text not null default 'draft' check(status in ('draft','submitted','in_review','changes_requested','published','suspended','archived')),quality_score integer not null default 0,rating numeric(3,2) not null default 0,review_count integer not null default 0,preview_config jsonb not null default '{}'::jsonb,license_config jsonb not null default '{}'::jsonb,moderation_notes text,published_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.marketplace_listing_versions(id uuid primary key default gen_random_uuid(),listing_id uuid not null references public.marketplace_listings(id) on delete cascade,version_number integer not null,snapshot jsonb not null,change_note text,created_by uuid references public.profiles(id) on delete set null,created_at timestamptz not null default now(),unique(listing_id,version_number));
create table if not exists public.marketplace_reviews(id uuid primary key default gen_random_uuid(),listing_id uuid not null references public.marketplace_listings(id) on delete cascade,reviewer_id uuid not null references public.profiles(id) on delete cascade,rating integer not null check(rating between 1 and 5),title text,body text,status text not null default 'published' check(status in ('pending','published','hidden','reported')),verified_purchase boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(listing_id,reviewer_id));
create table if not exists public.marketplace_moderation_cases(id uuid primary key default gen_random_uuid(),listing_id uuid not null references public.marketplace_listings(id) on delete cascade,status text not null default 'open' check(status in ('open','reviewing','approved','changes_requested','rejected','closed')),checks jsonb not null default '[]'::jsonb,assigned_to uuid references public.profiles(id) on delete set null,decision text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.enterprise_org_units(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,parent_id uuid references public.enterprise_org_units(id) on delete cascade,name text not null,unit_type text not null default 'team',settings jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.sso_configurations(id uuid primary key default gen_random_uuid(),organization_id uuid not null unique references public.organizations(id) on delete cascade,provider_type text not null check(provider_type in ('saml','oidc')),enabled boolean not null default false,issuer text,authorization_url text,token_url text,certificate text,client_id text,client_secret_encrypted text,domain_allowlist text[] not null default '{}',settings jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.public_api_keys(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,name text not null,key_prefix text not null,key_hash text not null unique,scopes text[] not null default '{}',last_used_at timestamptz,expires_at timestamptz,revoked_at timestamptz,created_by uuid references public.profiles(id) on delete set null,created_at timestamptz not null default now());
create table if not exists public.webhook_endpoints(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,name text not null,url text not null,events text[] not null default '{}',secret_hash text not null,enabled boolean not null default true,last_success_at timestamptz,last_failure_at timestamptz,failure_count integer not null default 0,created_by uuid references public.profiles(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.webhook_deliveries(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,endpoint_id uuid not null references public.webhook_endpoints(id) on delete cascade,event_id uuid,event_type text not null,payload jsonb not null,status text not null default 'queued' check(status in ('queued','sending','delivered','retry','failed','cancelled')),attempt_count integer not null default 0,next_attempt_at timestamptz not null default now(),response_status integer,response_body text,created_at timestamptz not null default now(),delivered_at timestamptz);
create table if not exists public.usage_quotas(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,metric text not null,period text not null default 'month',limit_value bigint not null,used_value bigint not null default 0,warning_percent integer not null default 85,period_started_at timestamptz not null default date_trunc('month',now()),period_ends_at timestamptz not null default date_trunc('month',now())+interval '1 month',updated_at timestamptz not null default now(),unique(organization_id,metric,period_started_at));
create table if not exists public.data_retention_policies(id uuid primary key default gen_random_uuid(),organization_id uuid not null unique references public.organizations(id) on delete cascade,analytics_days integer not null default 365,audit_days integer not null default 730,deleted_content_days integer not null default 30,legal_hold boolean not null default false,settings jsonb not null default '{}'::jsonb,updated_at timestamptz not null default now());
create table if not exists public.sla_incidents(id uuid primary key default gen_random_uuid(),organization_id uuid references public.organizations(id) on delete cascade,service text not null,severity text not null check(severity in ('minor','major','critical')),status text not null default 'open' check(status in ('open','monitoring','resolved')),started_at timestamptz not null default now(),resolved_at timestamptz,summary text not null,impact text,created_at timestamptz not null default now());
create index if not exists marketplace_listing_status_idx on public.marketplace_listings(status,published_at desc);create index if not exists webhook_delivery_queue_idx on public.webhook_deliveries(status,next_attempt_at);create index if not exists api_keys_org_idx on public.public_api_keys(organization_id,revoked_at);
alter table public.marketplace_listings enable row level security;alter table public.marketplace_listing_versions enable row level security;alter table public.marketplace_reviews enable row level security;alter table public.marketplace_moderation_cases enable row level security;alter table public.enterprise_org_units enable row level security;alter table public.sso_configurations enable row level security;alter table public.public_api_keys enable row level security;alter table public.webhook_endpoints enable row level security;alter table public.webhook_deliveries enable row level security;alter table public.usage_quotas enable row level security;alter table public.data_retention_policies enable row level security;alter table public.sla_incidents enable row level security;
create policy marketplace_public_read on public.marketplace_listings for select using(status='published' or public.is_org_member(organization_id));create policy marketplace_owner_write on public.marketplace_listings for all using(public.has_org_role(organization_id,array['owner','admin']::public.member_role[])) with check(public.has_org_role(organization_id,array['owner','admin']::public.member_role[]));create policy listing_versions_read on public.marketplace_listing_versions for select using(exists(select 1 from public.marketplace_listings l where l.id=listing_id and (l.status='published' or public.is_org_member(l.organization_id))));create policy listing_versions_write on public.marketplace_listing_versions for all using(exists(select 1 from public.marketplace_listings l where l.id=listing_id and public.has_org_role(l.organization_id,array['owner','admin']::public.member_role[]))) with check(true);
create policy marketplace_reviews_read on public.marketplace_reviews for select using(status='published' or reviewer_id=auth.uid());create policy marketplace_reviews_write on public.marketplace_reviews for all using(reviewer_id=auth.uid()) with check(reviewer_id=auth.uid());create policy moderation_admin on public.marketplace_moderation_cases for all using(public.is_platform_admin()) with check(public.is_platform_admin());
do $$ declare t text;begin foreach t in array array['enterprise_org_units','sso_configurations','public_api_keys','webhook_endpoints','webhook_deliveries','usage_quotas','data_retention_policies'] loop execute format('create policy %I_read on public.%I for select using(public.has_org_role(organization_id,array[''owner'',''admin'']::public.member_role[]))',t,t);execute format('create policy %I_write on public.%I for all using(public.has_org_role(organization_id,array[''owner'',''admin'']::public.member_role[])) with check(public.has_org_role(organization_id,array[''owner'',''admin'']::public.member_role[]))',t,t);end loop;end $$;
create policy sla_admin_read on public.sla_incidents for select using(organization_id is null or public.has_org_role(organization_id,array['owner','admin']::public.member_role[]));create policy sla_platform_write on public.sla_incidents for all using(public.is_platform_admin()) with check(public.is_platform_admin());
